synnaxlabs/synnax

.github/workflows/brew.publish.yaml

This commit addresses issue #229 by introducing a GitHub Action workflow file that automatically bumps the version of synnax in the homebrew tap. It uses a wrapper for the
`brew bump-formula-pr` cli command and requires a
**non-default** GitHub access token to access the separate homebrew tap repository.
The action secret `HOMEBREW_BUMP_TOKEN` needs to be added in order for this workflow to work.

[synnax] - Homebrew tap version bumping workflow

---

x/go/calc/calc.go
x/go/calc/calc_test.go

Operations supported:
- &&
- ||
- ==
- !=
- <
- <=
- \>
- \>=
- !
&& and || have a lower precedence than the other operators. For example,
- a == b && c == d would evaluate to (a == b) && (c == d), not ((a == b) && c) == d
- a && b == c && d would evaluate to (a && (b == c)) && d, not (a && b) == (c && d)

implement support for boolean expressions

---

driver/opc/util.cpp

PR to fix bad alloc issue occuring in opc/reader.cpp on  UA_Client_Service_read().
- Lack of type/null checking on longContext pointer caused unbounded memory allocation when casting to string
- fix: better null and type checking in the log adapter from the driver to the open62541 interface

better exception handling for customLogger

---

client/ts/src/channel/channel.spec.ts
client/ts/src/channel/retriever.ts
client/ts/src/channel/writer.ts
client/ts/src/client.ts

- [Linear Issue](ebonilla/sy-833-ts-delete-invalidation-on-channel-retrieve-cache)
We cache channels after retrieving them. If we deleted a retrieved channel, the cache entry would not be removed. This fix addresses that, along with updating the cache on renames.

[client/ts] - implemented channel retrieve cache invalidation

---

cesium/db.go
cesium/delete.go

- [Linear Issue](https://linear.app/synnaxlabs/issue/SY-840/deadlock-in-delete)
Cause was on close, mutex is locked on the database while existing already-scheduled garbage collection routines also need to lock the mutex. Fixed by first running DB shutdown then locking mutex for db close.
with necessary manual QA steps to test my change. - **NONE ADDED**

[cesium] - fixed a deadlock with garbage collection on cesium closing

---

cesium/db.go
cesium/gc_test.go
cesium/internal/unary/delete.go

- [SY-847](https://linear.app/synnaxlabs/issue/SY-847/[cesium]-relay-closing-race-condition)
We were shutting down the database signal context before closing the control digests – this deadlocked writes in the control digests which attempt to send to relay – which is already closed after the signal context is closed. This PR fixes this by closing the control digest before shutting down the signal context.

[cesium] - fixed a deadlock with relay on db closing

---

docs/site/src/pages/reference/device-drivers/opcua/connect-server.mdx

- **Linear Issue**: [SY-824](https://linear.app/synnaxlabs/issue/SY-824/site-small-note-box-in-opc-ua-documentation)
Made sure that the note box did not appear squished.

[docs/site] - Fixed small note box in OPC UA documentation

---

synnax/pkg/hardware/embedded/enabled.go

- Linear Issue: [SY-894](https://linear.app/synnaxlabs/issue/SY-894/fix-panic-on-out-of-index-logs-in-driver)
Fixed the embedded driver panicking on improperly formatted/empty log messages.

Sy 894 fix panic on out of index logs in driver

---

client/ts/src/auth/auth.ts
client/ts/src/errors.spec.ts
client/ts/src/errors.ts
client/ts/src/framer/streamProxy.ts
client/ts/src/framer/streamer.ts
client/ts/src/ranger/active.ts
console/src/group/ontology.tsx
console/src/hardware/ni/task/AnalogRead.tsx
console/src/hardware/ni/task/DigitalRead.tsx
console/src/hardware/ni/task/DigitalWrite.tsx
console/src/workspace/syncer.ts
drift/src/configureStore.ts
freighter/ts/src/errors.spec.ts
freighter/ts/src/errors.ts
freighter/ts/src/index.ts
freighter/ts/src/websocket.spec.ts

- Linear Issue: [SY-897](https://linear.app/synnaxlabs/issue/SY-897/ni-fix-channel-recreation-in-task-configuration-workflows)
Improves error matching by adding a new `matches` function instead of using `instanceof`. `instanceof` can cause problems when multiple projects that have different versions of dependencies are bundled together. In these cases, `instanceof` will not work. Instead, we match by the `type` filed on the error.

[ops/ts] - improved error matching semantics

---

console/src/layout/Window.tsx
console/src/palette/Palette.tsx
drift/src/state.ts
pluto/src/haul/Haul.tsx
pluto/src/os/Controls/Windows.tsx
x/ts/src/spatial/box/box.spec.ts
x/ts/src/spatial/box/box.ts

added auto-removal of minimized state on existing window creation
- Linear Issue: [SY-896](https://linear.app/synnaxlabs/issue/SY-896/fix-issues-with-drift-window-persistence)
Fixes issues hiding and showing drift windows by ensuring that windows that already exists, but are "recreated" are correctly un-minimized and centered in the viewport.
- [z] I have performed a self-review of my code.
- [z] I have added sufficient regression tests to cover the changes.
- [z] I have updated the [Release Candidate](/.github/PULL_REQUEST_TEMPLATE/rc.md) template

[drift] - added auto-removal of minimized state on existing window creation

---

.github/workflows/test.aspen.yaml

- [SY-892](https://linear.app/synnaxlabs/issue/SY-892/[ops]-wrong-name-for-aspen-test-workflow)
- **To be merged into main!!**
Our test Aspen was called Test Cesium and this PR fixes that
with necessary manual QA steps to test my change. - **N/A**

[ops] - typo in test aspen mistaken for test cesium

---

client/py/examples/control/press/simulated_daq.py
client/py/examples/control/tpc/simulated_daq.py
client/py/synnax/framer/streamer.py
freighter/py/freighter/stream.py
freighter/py/freighter/websocket.py

- Linear Issue: [SY-923](https://linear.app/synnaxlabs/issue/SY-923/fix-sync-websocket-received-method)
Adds optional timeout parameter to `streamer.read` that allows for checking received messages without blocking.

[freighter/py] - implemented websocket receive timeout

---

pluto/src/telem/client/cache/dynamic.spec.ts

- **Linear Issue**: [SY-920](https://linear.app/synnaxlabs/issue/SY-920/fix-failing-dynamic-cache-spec)
Made a timing test more lenient so it fails in CI less often.

Made the flushed timespan more lenient

---

.github/workflows/test.aspen.yaml
.github/workflows/test.cesium.yaml
.github/workflows/test.synnax.yaml
alamos/go/log.go
aspen/internal/cluster/gossip/gossip_test.go
cesium/cesium_suite_test.go
cesium/channel_test.go
cesium/gc_test.go
cesium/internal/domain/delete_test.go
cesium/internal/domain/file_controller_test.go
cesium/internal/domain/gc_test.go
cesium/internal/domain/index_persist_test.go
cesium/internal/domain/iterator_behavior_test.go
cesium/internal/domain/writer_behavior_test.go
cesium/internal/index/domain_test.go
cesium/internal/meta/meta_test.go
cesium/internal/unary/delete_test.go
cesium/internal/unary/gc_test.go
cesium/internal/unary/iterator_behavior_test.go
cesium/internal/unary/race_test.go
cesium/internal/unary/writer_behavior_test.go
cesium/internal/version/migration_test.go
cesium/writer_behavior_test.go
freighter/integration/main.go
synnax/cmd/instrumentation.go
synnax/cmd/internal/invariants/development.go
synnax/cmd/internal/invariants/production.go
x/go/testutil/instrumentation.go

- [SY-375](https://linear.app/synnaxlabs/issue/SY-375/[server]-register-global-zap-logger)
Initialized zap global logger when server starts.
**breaking changes**:
- freighter/integration has a global logger always configured to development mode.
with necessary manual QA steps to test my change. - **None aded**

Sy 375 server register global zap logger

---

client/py/pyproject.toml
client/py/synnax/framer/iterator.py
client/py/tests/test_framer.py

- **Linear Issue**: [SY-972](https://linear.app/synnaxlabs/issue/SY-972/hotfix-[py-client]-iterator-prev)
Our iterator `prev` command currently calls `NEXT` to the server. It should call `PREV`

[HOTFIX] - [client] - iterator `Prev` command

---

cesium/internal/unary/iterator.go
cesium/internal/unary/iterator_test.go

- **Linear Issue**: [SY-973](https://linear.app/synnaxlabs/issue/SY-973/[cesium]-iterator-seekge-and-seekle-clip-to-startend-of-resulting)
Originally, when SeekGE finds a domain that is greater than the provided timestamp but does not contain it, it leaves the iterator's view at the provided timestamp. This PR changes this behaviour so the iterator's view is set at the start/end of the sought domain instead.
A similar behaviour adjustment is put in place for SeekLE as well.

[cesium] - changed seekLE and seekGE behaviour when result is not exact

---

cesium/channel_test.go
cesium/delete_test.go
cesium/internal/unary/delete.go
cesium/internal/unary/iterator.go
cesium/iterator.go
cesium/iterator_test.go
cesium/options.go
cesium/writer.go
cesium/writer_test.go

- **Linear Issue**: [SY-948](https://linear.app/synnaxlabs/issue/SY-948/cesium-unit-test-review)
Added a SetAuthority method to cesium/writer – setAuthority is currently in use by the console (aether), but is not tested by any client or by cesium.
Added test cases where lacking

[cesium] - code cleanup

---

console/src/layout/migrations/v0.ts
console/src/lineplot/LinePlot.tsx
console/src/range/EditLayout.tsx
console/src/range/Select.tsx
console/src/range/external.ts
console/src/range/migrations/index.ts
console/src/range/migrations/v0.ts
console/src/range/selectors.ts
console/src/range/slice.ts
pluto/src/form/Field.tsx

- **Linear Issue**: [SY-922](https://linear.app/synnaxlabs/issue/SY-922/fix-creating-range-from-line-plot-context-menu)
Removed the buffer from the range console and allowed ranges to be passed directly through the create range window layout form.

SY-922 Fix Create Range from Line Plot Context Menu

---

.github/PULL_REQUEST_TEMPLATE/rc.md
cesium/writer_stream.go
x/go/telem/series.go

- **Linear Issue**: [SY-964]()
Maximum 2-3 sentence description describing the changes.
Server would panic when disconnecting an NI device which is in use by a read task in the server.  Added a check to `UpdateHighWater` to check for series length before using it to set the watermark.

[cesium] added length check for series when updating high watermark

---

.github/PULL_REQUEST_TEMPLATE/rc.md
console/package.json
console/src/cluster/slice.ts
console/src/docs/slice.ts
console/src/hooks/useLoadRemote.ts
console/src/layout/migrations/index.ts
console/src/layout/migrations/migrations.spec.ts
console/src/layout/slice.ts
console/src/lineplot/LinePlot.tsx
console/src/lineplot/migrations/index.ts
console/src/range/migrations/index.ts
console/src/schematic/migrations/index.ts
console/src/version/slice.ts
console/src/workspace/slice.ts
x/ts/package.json
x/ts/src/migrate/migrate.spec.ts
x/ts/src/migrate/migrate.ts

- **Linear Issue**: [SY-959](https://linear.app/synnaxlabs/issue/SY-959/[console]-old-workspaces-not-migrating-correctly)
How to Reproduce - Open Synnax version 23, create a workspace and add some schematics and line plots. Then, install Synnax version 24 and open the same workspace. Then, try to open one of the schematics or line plots.
Expected Behavior - The layouts should load in correctly.
Actual Behavior - You won't be able to load in any of the layouts.
This PR fixes this issue.

Sy 959 console old workspaces not migrating correctly

---

cesium/internal/core/frame.go
cesium/writer_stream.go
cesium/writer_test.go
x/go/telem/series.go
x/go/telem/series_factory.go

- **Linear Issue**: [SY-964]
Server would panic when disconnecting an NI device which is in use by a read task in the server. Added a check to UpdateHighWater to check for series length before using it to set the watermark.

sy-964 server panic ni disconnect

---

aspen/internal/cluster/cluster.go
aspen/internal/cluster/pledge/pledge_test.go
aspen/internal/cluster/store/store.go
aspen/internal/kv/gossip.go
aspen/internal/kv/store.go
synnax/pkg/distribution/cluster/ontology.go
x/go/store/store.go

- **Linear Issue**: [SY-1075](https://linear.app/synnaxlabs/issue/SY-1075/fix-aspen-concurrent-map-read-and-write)
Fixes an issue where the aspen store that holds information about a cluster concurrently reads and writes from a map. Adjusts the implementation of `PeekState` in `x/go/store` to hold a mutex until it is released. 

[aspen] - fixed issues with concurrent modification of cluster store

---

cesium/control.go
cesium/internal/unary/db.go
cesium/internal/unary/delete.go
cesium/internal/unary/open.go
cesium/internal/unary/writer.go
cesium/internal/virtual/db.go
cesium/internal/virtual/writer.go
cesium/open.go
cesium/writer_open.go
freighter/go/fhttp/router.go
freighter/go/fhttp/stream.go

- **Linear Issue**: [SY-1085](https://linear.app/synnaxlabs/issue/SY-1085/v27-server-fix-bad-bootup-from-prev-version)
Addresses two issues:
1. Cesium would panic when opening from a previous version that had an existing control digest channel. It would attempt to send a value to a go channel that didn't exist.
2. Fixes an issue where cesium would complain about open writers/iterators on Synnax DB shutdown. Adds a WaitGroup that waits for all streaming transports to shutdown before moving to the next steps. 

Sy 1085 v27 server fix bad bootup from prev version

---

pluto/src/select/Multiple.tsx

- **Linear Issue**: [SY-1089](https://linear.app/synnaxlabs/issue/SY-1089/pluto-fix-select-tag-close-removing-the-wrong-item)
Minor fix that addresses a bug when you remove a tag from a `Select.Multiple` and it removes the wrong item.

Pluto - Minor Select.Multiple Remove Fix

---

console/src/hardware/device/ontology.tsx
console/src/hardware/opc/task/ReadTask.tsx
console/src/hardware/task/Toolbar.tsx
console/src/hardware/task/common/common.tsx

- **Linear Issue**: [SY-1088](https://linear.app/synnaxlabs/issue/SY-1088/when-you-playpause-an-ni-task-and-clock-away-and-come-back-it-shows)
Fixes an issue where the correct task state would not show up in the dialog when switching to a different tab and coming back. 

Fix Play/Pause for NI Task

---

console/src/range/services/link.tsx

- **Linear Issue**: [SY-1092](https://linear.app/synnaxlabs/issue/SY-1092/adjust-range-link-handler)
Makes the link to a range open the overview page instead of adding the range to a new plot.

Sy 1092 adjust range link handler

---

console/src/confirm/Confirm.tsx

- **Linear Issue**: [SY-1087](https://linear.app/synnax/issue/SY-1087/[console]-deleting-workspace-caused-error-that-hard-reseting-didnt-fix)
Adds an explicit check for an undefined result in arguments for a confirmation modal. It resolves the confirmation to false if a valid result was not returned.

SY-1087 Fixed Issue with Undefined Result in Confirmation Arg

---

driver/ni/analog_read.cpp

- **Linear Issue**: [SY-1112]()
This pr fixes a bug that wouldn't allow ni analg read tasks to be constructed with float64 precision as frames were hard coded to only write float32 type series.

SY-1112 NI Analog Read - Allow for variable precision floating point

---

console/src/hardware/ni/device/ontology.tsx
console/src/hardware/ni/pallette.tsx
console/src/hardware/ni/task/AnalogRead.tsx
console/src/hardware/ni/task/DigitalRead.tsx
console/src/hardware/ni/task/DigitalWrite.tsx
console/src/hardware/opc/device/Browser.tsx
console/src/hardware/opc/device/ontology.tsx
console/src/hardware/opc/palette.tsx
console/src/hardware/opc/task/ReadTask.css
console/src/hardware/opc/task/ReadTask.tsx
console/src/hardware/task/common/common.css
console/src/hardware/task/common/common.tsx
console/src/hardware/task/ontology.tsx
console/src/lineplot/services/palette.tsx
pluto/src/dropdown/Dropdown.css

- **Linear Issue**: [SY-1132](https://linear.app/synnax/issue/SY-1132/fix-bad-pre-population-in-device-fields)
Previously, when you would click "Create X Task" on a device in the context menu, it would not populate the device field when creating a task. This fixes that issue, now the device field will be properly populated.

SY-1132 - fixed issues with device population when creating tasks

---

console/package.json
console/src/range/EditLayout.tsx
console/src/range/overview/Details.tsx
pluto/package.json
pluto/src/input/DateTime.tsx
pluto/src/input/Text.tsx
pluto/src/input/types.ts

- **Linear Issue**: [SY-1143](https://linear.app/synnax/issue/SY-1143/stop-flickering-on-range-dates)
Implements a change to the `DateTime` input so it only changes when the user blurs the input or hits the enter key. This fixes flickering issues when quickly editing range dates.

SY-1143 Added onlyChangeonBlur to DateTime input

---

console/package.json
pluto/package.json
pluto/src/vis/button/aether/button.ts
pluto/src/vis/schematic/Forms.tsx

- **Linear Issue**: [SY-1174](https://linear.app/synnax/issue/SY-1174/fix-button-triggering-logic-in-console)
Sometimes a button would trigger out of nowhere due to re-renders happening on different areas of the page. This issue fixes that.

[HOTFIX] Sy-1174 fix button triggering logic in console

---

README.md
client/cpp/channel/channel.h
client/cpp/framer/framer.h
client/cpp/ranger/ranger.h
client/py/examples/control/tpc/README.md
client/py/synnax/channel/client.py
client/py/synnax/ranger/client.py
client/ts/CONTRIBUTING.md
client/ts/README.md
client/ts/package.json
client/ts/src/channel/client.ts
console/README.md
docs/tech/README.md
freighter/README.md
synnax/README.md

1. Updated links to the documentation website in the repository ([SY-577](https://linear.app/synnax/issue/SY-577/fix-in-code-documentation-links)).
2. Updated TypeScript Client `package.json`, `README.md`, and made a separate `CONTRIBUTING.md` file ([SY-883](https://linear.app/synnax/issue/SY-883/fix-typescript-client-readme)).

SY-577 Documentation Links, SY-883 TypeScript README

---

console/package.json
console/src/hardware/ni/device/Configure.tsx

- **Linear Issue**: [SY-1212](https://linear.app/synnax/my-issues/assigned)
This pr fixes the issue where certain ni devices with limited "enriched" data stored will not populate all the necessary properties. Now they will be set to their default properties, rather than using enrich.

[HOTFIX] SY-1212 set ni device properties to default

---

driver/ni/analog_read.cpp
driver/ni/digital_read.cpp
driver/ni/digital_write.cpp
driver/ni/ni.cpp
driver/ni/ni.h
driver/ni/task.cpp

- **Linear Issue**: [SY-1129](https://linear.app/synnax/issue/SY-1129/[driver]-disable-enable-channels-in-ni-analog-read)
This pr fixes the issue where, if an ni channel is disabled, it still writes to the channel on the server.

SY 1129 allow ni channels to be enabled and disabled

---

pluto/src/color/Picker/Picker.tsx
pluto/src/vis/schematic/Forms.tsx
pluto/src/vis/schematic/Symbols.tsx
pluto/src/vis/schematic/primitives/Primitives.tsx
pluto/src/vis/schematic/registry.ts

- **Linear Issue**: [SY-1194](https://linear.app/synnax/issue/SY-1194/box-border-radius-tank-background-color)
Adjusted the border radius on the box and added a border radius picker. Also added a background color picker for the tank and the box.

SY-1194 Adjust Box Border Radius + Tank & Box Background Color

---

docs/site/src/pages/reference/console/schematics.mdx
pluto/src/input/DragButton.tsx
pluto/src/pluto/aether/pluto.ts
pluto/src/vis/light/aether/index.ts
pluto/src/vis/light/aether/light.ts
pluto/src/vis/light/index.ts
pluto/src/vis/light/use.ts
pluto/src/vis/schematic/Forms.tsx
pluto/src/vis/schematic/Symbols.tsx
pluto/src/vis/schematic/primitives/Primitives.css
pluto/src/vis/schematic/primitives/Primitives.tsx
pluto/src/vis/schematic/registry.ts

- **Linear Issue**: [SY-1098](https://linear.app/synnax/issue/SY-1098/add-ability-to-resize-any-schematic-symbol)
Added ability to resize (almost) any schematic symbols - buttons, switches, values, and setpoints still cannot be resized. Also refactored some code in relevant files.
NOTE: Previous versions of the schematic will have a `scale` of `null`, so the options for scaling them will not show up. I don't know a great way to fix this problem, and don't think it matters too much - all it means is that the elements created before this version gets released cannot be scaled. If someone wants to scale that element, they could delete it and replace it with a new one.
Please …

SY-1098 Add Ability to Resize Most Schematic Symbols

---

pluto/src/status/aether/aggregator.ts

- **Linear Issue**: [SY-1227](https://linear.app/synnax/issue/SY-1227/errors-that-cant-be-closed)
Unique keys on the aether side were generated using timestamps, which means that, occasionally, keys for two notifications would collide. This uses ID generation instead.

[pluto] - fixed unique ID generation in pluto statuses

---

console/src/layout/slice.ts

- **Linear Issue**: [SY-1159](https://linear.app/synnax/issue/SY-1159/schematic-cannot-get-edited-on-windows)
Fixes an issue where haul state gets incorrectly persisted, causing schematics not to be editable.

Sy 1159 schematic cannot get edited on windows

---

console/src/hardware/ni/task/ChannelForms.tsx

- **Linear Issue**: [SY-1285](https://linear.app/synnax/issue/SY-1285/opening-documentation-should-start-at-console-page)
Removed a duplicate form item for microphone channels in NI analog read task configuration.

SY-1302: Duplicate Terminal Configuration in NI Analog Read Microphone

---

console/src/range/Toolbar.tsx

- **Linear Issue**: [SY-1265](https://linear.app/synnax/issue/SY-1265/hide-view-details-and-create-child-range-for-a-local-range-in-range)
Removed the view details and create child range from context menu options for a local range in the range toolbar.

SY-1265: Remove "View Details" and "Create Child Range" from Local Range Context Menu

---

console/src/docs/Docs.tsx

- **Linear Issue**: [SY-1285](https://linear.app/synnax/issue/SY-1285/opening-documentation-should-start-at-console-page)
Opening documentation from the console now starts at the console page.

SY-1285: Opening Documentation Should Start at Console Page

---

console/src/lineplot/LinePlot.tsx

- **Linear Issue**: [SY-1282](https://linear.app/synnax/issue/SY-1282/line-plot-download-as-csv-should-suggest-better-file-name)
Suggested a better name for the CSV file when downloading data from a line plot as CSV.

SY-1282: Line Plot Download as CSV Should Suggest Better File Name

---

console/src/hardware/ni/task/types.ts

- **Linear Issue**: [SY-1321](https://linear.app/synnax/issue/SY-1321/alphabetize-ni-analog-read-channel-dropdown)
Alphabetized the types of NI analog read task channels in the channel dropdown selector.

SY-1321: Alphabetize NI Analog Read Types

---

console/src/channel/services/link.ts
console/src/link/link.tsx

- **Linear Issue**: [SY-1275](https://linear.app/synnax/issue/SY-1275/change-channel-deep-linking-line-plot-name)
Change the default line plot name used when channel deep linking.
The following makes sure that this feature does not break backwards compitability.

SY-1275 Change Channel Deep Linking Line Plot Name

---

console/src/lineplot/toolbar/Axes.tsx
pluto/src/select/Direction.tsx

- **Linear Issue**: [SY-1281](https://linear.app/synnax/issue/SY-1281/change-label-arrow-direction-under-line-plot-axes-tab)
Change the Pluto direction selector to have a the default y icon be up instead of down. Hide label direction selector for x-axis on Console line plot.

SY-1281 Change Label Arrow Direction under Line Plot Axes Tab

---

pluto/src/button/Link.tsx
pluto/src/input/Input.css

- **Linear Issue**: [SY-1263](https://linear.app/synnax/issue/SY-1263/open-links-in-range-overview-window)
Changed the coloring of input boxes so that the text color is the same as the input color. Also fixed an issue where links that do not have a scheme prepended are automatically prepended with HTTPS, which caused some issues with opening links in the range metadata overview.

SY-1263: Open Links in Range Overview Window

---

.github/workflows/deploy.console.yaml

- **Linear Issue**: [SY-1376](https://linear.app/synnax/issue/SY-1376/only-notarize-on-push)
Makes is to that MacOS builds only get notarized on push, preventing excessive CI times on pull requests.

[console/ops] - adjusted notarization behavior for MacOS in CI

---

client/ts/package.json
client/ts/src/errors.spec.ts
pnpm-lock.yaml

- **Linear Issue**: [SY-1187](https://linear.app/synnax/issue/SY-1187/verify-error-matching-works-with-notfounderror-on-windows)
Added a test to verify that error matching works on Windows. Ran the test on a local machine running Windows. Test is not currently run in CI on Windows because client tests are not run on Windows.

SY-1187 Verify Error Matching Works with `NotFoundError` on Windows

---

docs/site/src/pages/reference/console/clusters.mdx
docs/site/src/pages/reference/console/ui-overview.mdx

- **Linear Issue**: [SY-1030](https://linear.app/synnax/issue/SY-1030/deep-linking-support-for-windows)
Removed a note on the documentation site stating that deep linking is unavailable for Windows. Currently, deep linking works on Windows, although it forces a [new instance](https://v2.tauri.app/reference/javascript/deep-link/#--windows--linux-unsupported-the-os-will-spawn-a-new-app-instance-passing-the-url-as-a-cli-argument) of the Console to open instead of opening the linked item in the current window.

SY-1030 Remove Windows Deep Link Warning from Docs

---

console/src/lineplot/file.ts
console/src/schematic/file.ts
console/src/workspace/ontology.tsx

- **Linear Issue**: [SY-1288](https://linear.app/synnax/issue/SY-1288/load-workspace-before-creating-schematics-or-plots)
When loading a new visualization from the workspace resources toolbar, the current workspace will now be switched upon loading in that visualization.

SY-1288 Load Workspace Before Creating Schematics or Plots

---

docs/site/package.json
docs/site/src/components/PostHog.astro
docs/site/src/layouts/Root.astro
pnpm-lock.yaml

- **Linear Issue**: [SY-1381](https://linear.app/synnax/issue/SY-1381/add-product-analytics-to-documentation-site)
Adds posthog product analytics to documentation site

[docs/site] - added product analytics

---

console/src/cluster/external.ts
console/src/cluster/notification.tsx
console/src/store.ts
console/src/version/Badge.tsx
console/src/version/Info.tsx
console/src/version/Updater.tsx
console/src/version/external.ts
console/src/version/migrations/index.ts
console/src/version/migrations/migrations.spec.ts
console/src/version/migrations/v0.ts
console/src/version/migrations/v1.ts
console/src/version/selectors.ts
console/src/version/slice.ts
pluto/src/button/Button.tsx
x/media/src/Icon/index.tsx

- **Linear Issue**: [SY-1367](https://linear.app/synnax/issue/SY-1367/snooze-update-notifications)
Added a snooze button on the version update notification so that the version updates can be silenced.

SY-1367: Allow Silencing of Version Update Notification

---

.github/workflows/deploy.console.yaml

- **Linear Issue**: [SY-#](https://linear.app/synnax/issue/)
Please write a short (2-3 sentence) description describing the changes.

[ops/console] change runner for console deployment to macos-latest

---

console/package.json
pluto/package.json
pluto/src/dropdown/Dropdown.tsx

- **Linear Issue**: [SY-1434](https://linear.app/synnax/issue/SY-1434/hotfix-dropdown-positioning-on-macos)
Fixes incorrect dropdown positioning on MacOS due to inconsistencies in the "container-type" css property on WebKit and WebView.

[pluto] - hotfixed dropdown positioning on MacOS

---

console/src/hardware/labjack/device/Select.tsx
console/src/hardware/labjack/device/types.ts

- **Linear Issue**: [SY-1463](https://linear.app/synnax/issue/SY-1463/add-labjack-port-aliases)
Shows the alternative LabJack port names that show up on the device so that it's easier to figure out what things are.

[console] - added aliases to labjack port selection

---

console/package.json
console/src/lineplot/LinePlot.tsx
console/src/range/Toolbar.tsx

- **Linear Issue**: [SY-1435](https://linear.app/synnax/issue/SY-1435/fix-open-new-plot-on-range-highlight)
Fix an issue

SY-1435 Fix Add to New Plot on Line Plot Range Highlight

---

console/package.json
console/src/hardware/labjack/task/Read.tsx
console/src/hardware/ni/task/AnalogRead.tsx
pluto/src/dropdown/Dropdown.tsx

- **Linear Issue**: [SY-1444](https://linear.app/synnax/issue/SY-1444/fix-taring-on-multiple-channel-read-tasks)
Hotfix to allow taring of multiple channels on a read tasks. Work to fix the underlying bug in Pluto Forms should be done later.

SY-1444 Fix Taring on Multiple Channels

---

.github/workflows/deploy.console.yaml
.github/workflows/deploy.py.yaml

- **Linear Issue**: [SY-1365](https://linear.app/synnax/issue/1365)
This pr changes how workflows that make commits checkout the repository by passing in a deploy key that has been configured to allow for writes to `main`.

SY-1365 protect main branch but allow auto pushes from workflows

---

console/src/hardware/labjack/device/types.ts
console/src/hardware/labjack/task/Write.tsx

- **Linear Issue**: [SY-1502](https://linear.app/synnax/issue/SY-1502/fix-labjack-port-indices)
Fixes incorrect alternate names in LabJack Ports

[console] - fixed LabJack port indices

---

drift/src/tauri/index.ts

- **Linear Issue**: [SY-1544](https://linear.app/synnax/issue/SY-1544/fix-drift-logical-positioning)
Tauri has a bug where the `toLogical` and `toPhysical` methods on a position duplicate the X coordinate. This PR switches to using internal functions to calculate the logical position.

[drift/tauri] - fixed logical and physical position calculations

---

console/index.html
console/src-tauri/src/main.rs
console/src/layout/external.ts
console/src/layout/useDropOutside.ts
console/src/layouts/Main.tsx
console/src/palette/Palette.tsx
console/src/store.ts
drift/src/state.ts
drift/src/sync.ts
drift/src/tauri/index.ts
pluto/src/haul/Haul.tsx
pluto/src/vis/axis/canvas.ts

- **Linear Issue**: [SY-1554](https://linear.app/synnax/issue/SY-1554/remove-fullscreen-poll-from-drift-on-windows)
Fixes a few bugs and improves performance for a few console related tasks:
- On MacOS, we need to constantly poll for the windows Fullscreen state in order to make sure we correctly show and hide the traffic lights. On Windows, we don't need to do this, so I removed the fullscreen poll interval.
- On MacOS, we need to use an independent cursor tracking library to correctly position new windows when they are dragged out of the console. On Windows, we don't need to do this, so I removed that tracking. Ends up saving around 20% of an idle core - a lot.
- Fixe issues with the `useDropOutside` hook on windows that caused it to occasionally not detect the correct drop outside …

[console & drift] - various performance improvements

---

console/src/ontology/Tree.tsx
pluto/src/tree/core.ts

- **Linear Issue**: [SY-855](https://linear.app/synnax/issue/SY-855/give-items-in-resources-tree-unique-keys)
Fixed a rendering issue where different items in the resources toolbar had the same key.

fix(resources tree): give different items different keys

---

pluto/src/vis/schematic/Symbols.tsx
pluto/src/vis/schematic/primitives/Primitives.tsx
pluto/src/vis/schematic/registry.ts

- **Linear Issue**: [SY-1560](https://linear.app/synnax/issue/SY-1560/t-junction)
Simple T-Junction Schematic Symbol

[pluto] - added T-Junction schematic symbol

---

docs/site/src/pages/reference/console/line-plots.mdx
docs/site/src/pages/reference/console/logs.mdx
docs/site/src/pages/reference/console/schematics.mdx
docs/site/src/pages/reference/console/tables.mdx
docs/site/src/pages/reference/console/workspaces.mdx

- **Linear Issue**: [SY-1609](https://linear.app/synnax/issue/SY-1609/workspace-saving-documentation-to-website)
Added information about visualizations not getting saved unless workspaces are to the documentation site. Also fixed some formatting issues and typos.

SY-1609 Add Workspace Saving Information to Documentation Website

---

pluto/src/vis/schematic/Forms.tsx
pluto/src/vis/schematic/Symbols.tsx

- **Linear Issue**: [SY-1610](https://linear.app/synnax/issue/SY-1610/fix-label-width-on-schematic)
Fixes an issue where labels on the schematic would wrap too early.
- [x I have added relevant tests to cover the changes to CI.

[pluto] - fixed issues with label wrapping

---

console/package.json
drift/package.json
drift/src/tauri/index.ts

- **Linear Issue**: [SY-1608](https://linear.app/synnax/issue/SY-1608/drift-fix-window-positioning)
Fixes an issue where newly created windows receive positions that are _very, very, very_ negative values. This issue causes the Tauri drift runtime to block such absurd positions, and defaults to positioning the window at { x:0, y: 0} when it encounters such a case. It doesn't fix the underlying issue, but it does prevent our users from losing their windows randomly.

[drift] - fixed windows appearing out of bounds

---

pluto/package.json
pluto/src/breadcrumb/Breadcrumb.tsx

- **Linear Issue**: [SY-1606](https://linear.app/synnax/issue/SY-1606/capitalize-documentation-site-breadcrumbs)
Fix breadcrumbs on documentation site, live version looks ugly

SY-1606 Capitalize Documentation Site Breadcrumbs

---

pluto/src/input/Switch.tsx

- **Linear Issue**: [SY-1646](https://linear.app/synnax/issue/SY-1646/disable-form-switch-fields-when-form-mode-is-preview)
Disable a switch input when the variant is preview.

SY 1646 Disable Switch Fields when Variant Is Preview

---

console/package.json
pluto/package.json
pluto/src/text/Editable.css
pluto/src/text/Editable.tsx
pluto/src/util/reflow.ts
pluto/src/vis/diagram/Diagram.tsx
pluto/src/vis/schematic/Forms.tsx
pluto/src/vis/schematic/Grid.tsx
pluto/src/vis/schematic/Symbols.css
pluto/src/vis/schematic/Symbols.tsx
pluto/src/vis/schematic/registry.ts

- **Linear Issue**: [SY-1658](https://linear.app/synnax/issue/SY-1658/fix-schematic-label-positioning-and-remove-snap-to-grid)
- Fix issues with the schematic label positioning
- Remove schematic snap to grid
- Fix issue with the clickable prop being passed into schematic previews.

SY-1658 Fix Schematic Label Positioning and Remove Snap To Grid

---

console/package.json
console/src/schematic/migrations/index.ts
console/src/schematic/migrations/migrations.spec.ts
console/src/schematic/migrations/v0.ts
console/src/schematic/migrations/v1.ts
console/src/schematic/migrations/v2.ts
console/src/schematic/migrations/v3.ts

- **Linear Issue**: [SY-1660](sy-1660-remove-bad-edges-and-nodes-when-importing-schematics
Remove bad edges and nodes when parsing a schematic JSON file.

SY-1660 Remove Bad Edges and Nodes when Importing Schematics

---

client/ts/src/ranger/client.ts
console/src/range/overview/ChildRanges.tsx
console/src/range/overview/Snapshots.tsx
x/ts/src/telem/telem.ts

- **Linear Issue**: [SY-1661](https://linear.app/synnax/issue/SY-1661/sort-child-ranges-in-range-overview-by-start-time)
Sort child ranges in the range overview by the start time of the range

SY-1661: Sort Child Ranges in Range Overview by Start Time

---

docs/site/.astro/settings.json
docs/site/src/components/console/OSDownloadButton.tsx

- **Linear Issue**: [SY-1673](https://linear.app/synnax/issue/SY-1673/docs-switch-to-using-dmg-over-app-file-on-download)
Downloading a DMG is a nicer UX than downloading a `.app` file as it prompts you to drag it into the `applications` folder, making sure auto-update works correctly.

[docs/site] - updated console download url to use DMG on MacOS

---

driver/labjack/reader.h
driver/labjack/reader_source.cpp
driver/labjack/reader_task.cpp
driver/labjack/scanner.cpp
driver/labjack/writer.h
driver/labjack/writer_sink.cpp
driver/labjack/writer_task.cpp

- **Linear Issue**: [SY-1647](https://linear.app/synnax/issue/1647)
This PR checks if channels are enabled and returns an error on configure if you enabled channels are passed in. Also refactors some of the error logging in labjack tasks. 

SY-1647 labjack error on all disabled channels in task

---

console/src/schematic/toolbar/Symbols.css
console/src/schematic/toolbar/Symbols.tsx
pluto/src/vis/schematic/Forms.tsx
pluto/src/vis/schematic/Symbols.tsx
pluto/src/vis/schematic/primitives/Primitives.tsx

- **Linear Issue**: [SY-1674](https://linear.app/synnax/issue/SY-1674/add-more-attachment-points-to-schematic-symbols)
Adds more attachment points to the schematic cylinder as requested by a customer.

Sy 1674 add more attachment points to schematic symbols

---

console/src/notifications/Notifications.tsx
console/src/version/Updater.tsx

- **Linear Issue**: [SY-1669](https://linear.app/synnax/issue/SY-1669/close-update-available-notification-when-you-click-snooze)
Fixed an issue where the version update notification remained open even after hitting the snooze action.

fix(console): Close Version Update Notification when Clicking Snooze

---

pluto/src/vis/schematic/Forms.tsx

- **Linear Issue**: [SY-1639](https://linear.app/synnax/issue/SY-1639/remove-label-direction-from-off-page-reference-element)
Remove the Label Direction Selection from the Off Page Reference Schematic Form.

fix(console): remove unneeded label direction in off page reference form

---

pluto/src/select/Button.tsx

- **Linear Issue**: [SY-1676](https://linear.app/synnax/issue/SY-1676/connect-opc-ua-server-modal-is-messed-up)
Fixes issues with the Select.Button not packing elements correctly. 

Sy 1676 connect opc ua server modal is messed up

---

console/src/hardware/task/Toolbar.tsx
console/src/hardware/task/ontology.tsx

- **Linear Issue**: [SY-1697](https://linear.app/synnax/issue/SY-1697/snapshots-should-not-appear-in-task-toolbar)
- Added an edit configuration menu item to the task ontology context menu
- Removed snapshots from the task toolbar

SY-1697: Add Edit Configuration to Task Ontology Context Menu and Remove Snapshots from Task Toolbar

---

console/src/Console.tsx
pluto/src/text/Editable.css
pluto/src/text/Editable.tsx
pluto/src/vis/schematic/Symbols.css

- **Linear Issue**: [SY-1681](https://linear.app/synnax/issue/SY-1681/fix-range-rename-in-toolbar)
Fixes text artifacting when renaming a range on macos. 

Sy 1681 fix range rename in toolbar

---

pluto/src/vis/lineplot/aether/YAxis.ts

- **Linear Issue**: [SY-1698](https://linear.app/synnax/issue/SY-1698/fix-cmd-channel-only-will-not-display-on-plot-until-written-to)
Fixes an issue where a channel with no data will override the bounds of all other channels in a plot, leading the plot to show the default range as opposed to the viable range of the channels that do have data. 

Sy 1698 fix cmd channel only will not display on plot until written

---

client/ts/src/index.ts
client/ts/src/ontology/group/payload.ts
console/src/group/ontology.tsx

- **Linear Issue**: [SY-1684](https://linear.app/synnax/issue/SY-1684/cannot-drag-groups)
Fixes an issue where groups cannot be dragged. 

Sy 1684 cannot drag groups

---

console/src/ontology/Tree.tsx
pluto/src/text/Editable.tsx

- **Linear Issue**: [SY-1680](https://linear.app/synnax/issue/SY-1680/fix-grouping-on-multiple-channels)
Fixes issue where grouping elements and then leaving a blank name caused problems.

[pluto] - fixed creating groups with no name in ontology failing

---

pluto/src/align/Space.spec.tsx
pluto/src/align/Space.tsx

- **Linear Issue**: [SY-1675](https://linear.app/synnax/issue/SY-1700/fix-spacing-on-table-form)
@pjdotson you noted this in a different pull request and I forgot to fix. Now it's fixed. 

Sy 1700 fix spacing on table form

---

console/src/lineplot/file.ts
console/src/lineplot/services/palette.tsx
console/src/schematic/file.ts
console/src/schematic/services/palette.tsx

- **Linear Issue**: [SY-1704]()https://linear.app/synnax/issue/SY-1704/import-lineplotschematic-command-not-available-from-palette)
Import line plot and schematic now available from command line. 

Sy 1704 import lineplotschematic command not available from palette

---

pluto/src/telem/control/aether/controller.ts

- **Linear Issue**: [SY-1679](https://linear.app/synnax/issue/SY-1679/persist-commands-to-disk-for-write-tasks)
Adds auto commit to the pluto controller, making schematic commands automatically persisted to disk.

Sy 1679 persist commands to disk for write tasks

---

console/src/layout/middleware.ts

- **Linear Issue**: [SY-1699](https://linear.app/synnax/issue/SY-1699/fix-blank-dangling-popped-out-windows-when-switching-workspaces)
Makes sure that windows get closed when switching workspaces.

[console] - made sure that windows get closed on an empty workspace

---

pluto/src/status/aether/aggregator.ts

- **Linear Issue**: [SY-1675](https://linear.app/synnax/issue/SY-1707/fix-duplicate-keys-in-aether-status-aggregation)
Fixes duplicate keys in aether status aggregation causing the user to not be able to dismiss notifications. 

[pluto] - made sure specs are always assigned a unique key

---

client/py/examples/opcua/read_task.py
console/src/hardware/labjack/task/Read.tsx
console/src/hardware/labjack/task/Write.tsx
console/src/hardware/ni/task/AnalogRead.tsx
console/src/hardware/ni/task/DigitalRead.tsx
console/src/hardware/ni/task/DigitalWrite.tsx
console/src/hardware/ni/task/common.tsx
console/src/hardware/opc/device/Configure.tsx
console/src/hardware/opc/task/Read.tsx
console/src/hardware/opc/task/Write.tsx
console/src/hardware/task/ontology.tsx
pluto/src/input/Input.css
pluto/src/select/Button.tsx

- **Linear Issue**: [SY-1690](https://linear.app/synnax/issue/SY-1690/disable-editing-channel-lists-in-task-snapshot)
Made sure all task snapshots were disabled from editing

Disable Editing Channel Lists in Task Snapshot

---

console/package.json
console/src/Console.tsx
pluto/package.json
pluto/src/channel/LinePlot.tsx
pluto/src/header/Header.css
pluto/src/vis/rule/Rule.css
pluto/src/vis/rule/Rule.tsx
pluto/src/vis/rule/aether/aether.ts

- **Linear Issue**: [SY-1720](https://linear.app/synnax/issue/SY-1720/fix-annotation-grid-positioning)
Fixes an issue where enabling and disabling the title on the plot itself results in the annotation being incorrectly positioned.

[pluto] - fixed annotation positioning with dynamic grid items

---

console/src/channel/Create.tsx
pluto/src/select/DataType.tsx

- **Linear Issue**: [SY-1470](https://linear.app/synnax/issue/SY-1470/block-variable-length-channel-in-console-channel-creation)
Block the creation of persisted, variable-length channels (JSONs, strings) in the Console create channel modal.

SY-1470 Block Variable Length Persisted Channel in Console Channel Creation

---

console/src/schematic/Schematic.tsx
console/src/schematic/selectors.ts
console/src/schematic/toolbar/Toolbar.tsx

- **Linear Issue**: [SY-1586](https://linear.app/synnax/issue/SY-1586/renaming-schematic-snapshots-from-tab-name-does-not-work)
Allow Schematic Snapshots to be renamed from their tab. Change Schematic toolbar to hide editing option text for a snapshot.

SY-1586 Allow Renaming Schematic Snapshots from Tab Name

---

console/src/link/Buttons.tsx
console/src/schematic/external.ts
console/src/schematic/services/ontology.tsx
console/src/schematic/toolbar/Toolbar.tsx
console/src/schematic/useRangeSnapshot.ts

- **Linear Issue**: [SY-1178](https://linear.app/synnax/issue/SY-1178/add-snapshot-to-schematic-toolbar)
Moved logic for snapshotting a schematic to a range to a separate hook.
Added a range button to the schematic toolbar header that let's the user snapshot the schematic to the

SY-1178 Add Snapshot to Schematic Toolbar

---

console/src/Console.tsx
console/src/cluster/Connect.tsx
console/src/cluster/Dropdown.tsx
console/src/cluster/external.ts
console/src/cluster/migrations/index.ts
console/src/cluster/migrations/migrations.spec.ts
console/src/cluster/migrations/v0.ts
console/src/cluster/migrations/v1.ts
console/src/cluster/migrations/v2.ts
console/src/cluster/selectors.ts
console/src/cluster/slice.ts
console/src/cluster/useSyncClusterKey.ts
console/src/layouts/Main.tsx
console/src/link/link.tsx
console/src/store.ts

- **Linear Issue**: [SY-1509](https://linear.app/synnax/issue/SY-1509/add-demo-cluster-to-selector)
- **Linear Issue**: [SY-1270](https://linear.app/synnax/issue/SY-1270/link-copying-local-cluster)
- Added a demo cluster to the default cluster list
- Fixed issues where the permanent store of the local cluster in the console state was LOCAL instead of the actual cluster key
- Chose better state structure for the cluster store slice (before, name was duplicated twice).

SY-1509 Add Demo Cluster to Default Clusters and Fix Issues with Copying Local Cluster Link

---

console/package.json
console/src/lineplot/LinePlot.tsx
console/src/log/Log.tsx
console/src/schematic/Schematic.tsx
console/src/schematic/services/palette.tsx
console/src/table/Table.tsx

- **Linear Issue**: [SY-1728](https://linear.app/synnax/issue/SY-1728/fix-schematic-import-causing-new-window)
Schematics with empty keys (`""`) get imported with that as their key, which causes funky behaviors with pre-rendered windows.

[console] - fixed issues with importing schematics with empty keys

---

console/src/layout/migrations/v0.ts
console/src/version/Info.tsx
console/src/workspace/syncer.ts

- **Linear Issue**: [SY-1278](https://linear.app/synnax/issue/SY-1278/clear-modals-when-switching-workspaces)
Adds the ability to exclude a layout from the workspace, and automatically removes all modals from the workspace.

[console] - added workspace exclusion functionality

---

console/src/ontology/Tree.tsx
pluto/src/tree/Tree.spec.tsx
pluto/src/tree/Tree.tsx
pluto/src/tree/core.ts

- **Linear Issue**: [SY-850](https://linear.app/synnax/issue/SY-850/position-groups-above-items-in-resources-tree)
Position groups above standalone items in ontology resources tree.

Sy 850 position groups above items in resources tree

---

client/py/poetry.lock
client/py/pyproject.toml
client/py/synnax/telem/telem.py

- **Linear Issue**: [SY-1757](https://linear.app/synnax/issue/SY-1757/upgrade-to-numpy-2)
Upgrades the Synnax python client to use numpy version 2.

[client/py] - upgraded to python 3.12

---

client/py/poetry.lock
client/py/pyproject.toml
client/py/synnax/telem/telem.py

The `pick` dependency was causing problems with 3.13. Turns out we didn't need that dependency.

Sy 1757 upgrade to numpy 2

---

pluto/src/table/aether/Table.ts
pluto/src/vis/lineplot/aether/LinePlot.ts
pluto/src/vis/value/aether/value.ts

- **Linear Issue**: [SY-1760](https://linear.app/synnax/issue/SY-1760/table-render-loop-doesnt-garbage-correctly)
Fixes an issue where the table render loop continues to render even after it gets deleted. Resolved by doing two things:
1. Skipping renders if the table is not deleted (this is a failsafe, which makes sure even if we haven't stopped telemetry sources correctly the table won't render again).
2. _The actual fix_ -> Make sure we cleaned up the color source telemetry and stop listening on the aether value component. 

[pluto] - fixed issues with table rendering

---

pluto/src/vis/diagram/edge/paths.tsx

- **Linear Issue**: [SY-1766](https://linear.app/synnax/issue/SY-1766/fix-schematic-edge-coloring)
Fixes schematic edge coloring not working correctly on lines with embedded symbols.

[pluto] - fixed schematic edge coloring

---

console/src/group/ontology.tsx
console/src/lineplot/services/ontology.tsx
console/src/log/services/ontology.tsx
console/src/schematic/services/ontology.tsx
console/src/table/services/ontology.tsx

- **Linear Issue**: [SY-1776](https://linear.app/synnax/issue/SY-1776/add-group-context-menu-item-to-visualizations)
Add group item to visualization context menu and format some code.

SY-1776 Add Group Item to Visualization Context Menus

---

pluto/src/vis/schematic/primitives/Primitives.tsx

…oning
- **Linear Issue: Weird Multi-Drag Out in Symbol Previews**: [SY-1786](https://linear.app/synnax/issue/SY-1786/weird-multi-drag-out-in-symbol-previews)
- **Linear Issue: Cylinder Preview is Very Small**: [SY-1785](https://linear.app/synnax/issue/SY-1785/cylinder-preview-is-very-small)
- **Linear Issue: Fix Randomly Appearing F in Previews**: [SY-1784](https://linear.app/synnax/issue/SY-1784/fix-randomly-appearing-f-in-previews)
- **Linear Issue: Fix Tank Endpoint Positioning**: [SY-1782](https://linear.app/synnax/issue/SY-1782/fix-tank-endpoint-positioning)
Fixes a number of issues related to schematic symbols discovered in v0.37 QA.
1. Dragging out flow symbols from library would cause multiple symbols to appear in preview.
2. Cylinder preview in symbols library was very small.
3. …

rSy 1784 fix randomly appearing f in previews

---

pluto/src/vis/schematic/Symbols.tsx

- **Linear Issue**: [SY-1783](https://linear.app/synnax/issue/SY-1783/align-text-box-preview-in-center)
Fixes the text box preview in the symbols library so that it remains aligned in the center. 

[pluto] - fixed text box preview alignment

---

pluto/src/input/Text.tsx
pluto/src/vis/schematic/primitives/Primitives.tsx

- **Linear Issue**: [SY-1779](https://linear.app/synnax/issue/SY-1779/fix-metadata-link-highlight)
Fixes an issue caused by changes to the input element for adding better highlighting to the schematic endpoint. This cause the highlight in the range meta data links to not turn blue. 

[pluto] - fixed meta data link highlight

---

console/src/log/Toolbar.tsx
console/src/schematic/toolbar/Toolbar.tsx

- **Linear Issue**: [SY-1792](https://linear.app/synnax/issue/SY-1792/minified-react-error-310-when-opening-workspace-from-search-bar)
We were conditionally returning before a hook call in the schematic toolbar.

Sy 1792 minified react error 310 when opening workspace from search

---

console/src/layout/Modal.tsx
pluto/package.json
pluto/src/modal/Modal.tsx
pluto/src/util/FocusTrap.tsx
pnpm-lock.yaml

- **Linear Issue**: [SY-1769](https://linear.app/synnax/issue/SY-1769/enter-key-causes-delete-modal-to-close-prematurely)
Removes the focus trap dependency until we can better handle side effects.

SY 1769 - Remove Focus Trap

---

synnax/pkg/distribution/distribution.go
synnax/pkg/distribution/ontology/group/service.go
synnax/pkg/service/hardware/device/device.go
synnax/pkg/service/hardware/device/device_suite_test.go
synnax/pkg/service/hardware/device/device_test.go
synnax/pkg/service/hardware/device/service.go
synnax/pkg/service/hardware/device/writer.go
synnax/pkg/service/hardware/rack/rack_test.go

- **Linear Issue**: [SY-1771](https://linear.app/synnax/issue/SY-1771/bad-ontology-relationship-created-on-grouped-device)
Fixes an issue where grouping a device before configuring it caused duplicate ontology relationships to appear. Also supplements device test cases.

Sy 1771 bad ontology relationship created on grouped device

---

pluto/src/theming/Provider.tsx
pluto/src/theming/theme.css
x/ts/src/caseconv/caseconv.spec.ts
x/ts/src/caseconv/caseconv.ts

- **Linear Issue**: [SY-1797](https://linear.app/synnax/issue/SY-1797/fix-box-shadows-on-windows)
Fixes bad box shadows when toggling the color theme on windows.

[pluto] - fixed issues with bad box shadows under different themes

---

client/py/examples/dev/create_device.py
console/src/hardware/ni/task/DigitalWrite.tsx

- **Linear Issue**: [SY-1795](https://linear.app/synnax/issue/SY-1795/changing-port-in-digital-write-task-does-not-change-channels-in)
Fix some issues with the channel list not updating on forms

Fix Channel List on NI Digital Write Task

---

console/src/schematic/toolbar/Toolbar.tsx

- **Linear Issue**: [SY-1787](https://linear.app/synnax/issue/SY-1787/prevent-snapshot-of-schematics-outside-of-workspace-in-toolbar)
Added a short useEffect in schematic toolbar to check if a schematic exists on server

SY-1787 Prevent Snapshot of Schematics from Toolbar Outside of Workspace

---

pluto/src/input/Input.spec.tsx
pluto/src/input/Numeric.tsx

- **Linear Issue**: [SY-1799](https://linear.app/synnax/issue/SY-1799/entering-string-in-setpoint-causes-crash)
Turns out that you could enter quotations into the numeric input (`""`) and it would call the `onChange` handler with an empty string. This PR fixes that. 

[pluto] - fixed input onChange handler firing on empty strings

---

.vscode/synnax.code-workspace
pluto/src/telem/control/aether/controller.ts
pluto/src/vis/setpoint/aether/setpoint.ts

- **Linear Issue**: [SY-1805](https://linear.app/synnax/issue/SY-1805/fix-setpoint-over-activating)
Fixed an issue where the setpoint component would fire even if the button was not clicked.

Sy 1805 fix setpoint over activating

---

console/src/schematic/toolbar/Toolbar.tsx

- **Linear Issue**: [SY-1806](https://linear.app/synnax/issue/SY-1806/remove-schematic-snapshot-to-range)
Remove schematic snapshot from range from range toolbar

Remove Range Snapshot from Schematic Toolbar

---

pluto/src/haul/Haul.tsx

- **Linear Issue**: [SY-1788](https://linear.app/synnax/issue/SY-1788/file-drop-does-not-work-correctly-on-windows)
Fixes file drag and drop on console mosaic on windows.

Sy 1788 file drop does not work correctly on windows

---

console/src/schematic/slice.ts
pluto/src/color/core/color.spec.ts
pluto/src/color/core/color.ts

- **Linear Issue**: [SY-1767](https://linear.app/synnax/issue/SY-1800/lower-contrast-threshold-to-trigger-schematic-color-change)
When we change the theme from light to dark or vice versa, we need to change some of the low contrast schematic components to white or black. Previously we just used a contrast threshold to do this, but this changed elements that were yellow or pink in color. Now we do a 'grayness' check instead that ensures we only change grays.

Sy 1800 lower contrast threshold to trigger schematic color change

---

driver/opc/writer.h
driver/opc/writer_sink.cpp

- **Linear Issue**: [SY-1809](https://linear.app/synnax/issue/SY-1809/opc-ua-write-value-copy)

[driver/opc] use scalarcopy instead of set scalar

---

client/py/pyproject.toml
client/py/synnax/cli/ingest.py
client/py/synnax/cli/login.py
client/py/synnax/cli/ts_convert.py
client/py/synnax/cli/warning.py
docs/site/src/pages/guides/analyst/exploratory-analysis-in-python.mdx
docs/site/src/pages/reference/python-client/get-started.mdx

- **Linear Issue**: [SY-1823](https://linear.app/synnax/issue/SY-1823/python-and-server-cli-name-conflict)
Added a short deprecation warning for the `synnax` and `synnaxkit` Python CLI command, and made the new default command `sy`.

SY-1823 Add Deprecation Warning to `synnax` and `synnaxkit` Python CLI Names

---

console/src/Console.tsx
console/src/schematic/Schematic.tsx
console/src/schematic/slice.ts

- **Linear Issue**: [SY-325](https://linear.app/synnax/issue/SY-325/⌘-a-to-select-all-elements)
Adds the `Control + A` (Windows) and `Cmd + A` (MacOS) commands to select all schematic elements.

Sy 325 a to select all elements

---

client/ts/src/framer/frame.ts
console/src/hardware/ni/task/AnalogRead.tsx
console/src/layouts/GetStarted.tsx
console/src/lineplot/LinePlot.tsx
console/src/lineplot/download.ts
console/src/lineplot/slice.ts
console/src/ontology/ContextMenu.tsx
console/src/ontology/Tree.tsx
console/src/ontology/builtin/ontology.tsx
console/src/ontology/hooks.ts
console/src/range/overview/Labels.tsx
console/src/workspace/Create.tsx
console/src/workspace/Selector.tsx
console/src/workspace/services/palette.tsx
drift/src/sync.ts
pluto/src/channel/Select.tsx
pluto/src/label/Select.tsx
pluto/src/list/useSelect.ts
pluto/src/menu/ContextMenu.tsx
pluto/src/ranger/Select.tsx
pluto/src/telem/control/Legend.tsx
pluto/src/telem/control/aether/state.ts
pluto/src/tree/Tree.tsx
pluto/src/tree/core.ts
pluto/src/triggers/hooks.tsx
x/ts/src/compare/compare.ts
x/ts/src/unique/index.ts
x/ts/src/unique/unique.spec.ts
x/ts/src/unique/unique.ts
x/ts/vite.config.ts

- **Linear Issue**: [SY-1835](https://linear.app/synnax/issue/SY-1835/fix-duplicated-items-in-resources-tree)
Fix duplicated items in resources tree by making sure when nodes get added to the tree, only nodes with different keys get added.

SY-1835 Fix Duplicated Items in Resources Tree

---

drift/src/tauri/index.ts

- **Linear Issue**: [SY-1891](https://linear.app/synnax/issue/SY-1891/drift-remember-monitor-locations)
Makes it so that drift properly positions windows for workspaces and persisted state on multiple monitors

SY-1891 - Drift - Correct Window Positioning for Multi-Monitor Setups

---

console/src/lineplot/services/ontology.tsx

- **Linear Issue**: [SY-1907](https://linear.app/synnax/issue/SY-1907/cannot-delete-an-line-plots)
Fixes a regression introduced on 1/6/25 that incorrectly parses a resource key as the 'key' section of the ontology ID as opposed to the entire ID.

SY-1907 Cannot Delete any Line Plots

---

pluto/src/button/Icon.tsx
pluto/src/vis/schematic/primitives/Primitives.tsx
pluto/src/vis/schematic/registry.ts

- **Linear Issue**: [SY-1919](https://linear.app/synnax/issue/SY-1919/fix-dom-warnings)
- Fixed React props that were hyphenated instead of camelCase.
- Re wrapped `Buttton.Icon` in a tooltip component.
- Removed `clickable` prop from some schematic elements

SY-1919 Fix DOM Warnings

---

console/src/persist/state.ts

- **Linear Issue**: [SY-1924](https://linear.app/synnax/issue/SY-1924/fix-clear-local-storage-command)
Fixes issues clearing local storage, and makes sure that initial state gets properly copied to avoid issues with readonly initial state fields. 

SY-1924 Fix Clear Local Storage Command

---

synnax/pkg/api/hardware.go
synnax/pkg/distribution/channel/lease_proxy.go
synnax/pkg/distribution/ontology/group/group_suite_test.go
synnax/pkg/distribution/ontology/group/group_test.go
synnax/pkg/distribution/ontology/group/service.go
synnax/pkg/distribution/ontology/schema/resource_test.go
synnax/pkg/service/hardware/device/device.go
synnax/pkg/service/hardware/device/ontology.go
synnax/pkg/service/hardware/device/retrieve.go
synnax/pkg/service/hardware/device/service.go
synnax/pkg/service/hardware/device/writer.go
synnax/pkg/service/hardware/rack/ontology.go
synnax/pkg/service/hardware/rack/rack.go
synnax/pkg/service/hardware/rack/retrieve.go
synnax/pkg/service/hardware/rack/service.go
synnax/pkg/service/hardware/rack/writer.go
synnax/pkg/service/hardware/service.go
synnax/pkg/service/hardware/task/ontology.go
synnax/pkg/service/hardware/task/retrieve.go
synnax/pkg/service/hardware/task/service.go
synnax/pkg/service/hardware/task/task.go
synnax/pkg/service/hardware/task/writer.go

- **Linear Issue**: [SY-1935](https://linear.app/synnax/issue/SY-1935/prevent-non-empty-groups-from-being-deleted)
Prevents groups that still have children from being deleted. 

SY-1935 - Prevent Non-Empty Groups from Being Deleted

---

pluto/src/text/Editable.tsx
pluto/src/triggers/Provider.tsx

- **Linear Issue**: [SY-1934](https://linear.app/synnax/issue/SY-1934/fix-resource-grouping)
1. Pressed down on Shift
2. You selected several resources in the tree
3. Grouped them
4. Renamed the group
5. Hit enter
6. Let go of shift
The Triggers system would not detect that you released the shift key, causing problems with expanding and contracting groups. This removes a propagation/default behavior stopper in the editable text component, which fixes that issue. Unfortunately, this might have unexpected side effects that are difficult to track. 

SY-1934 - Fix Shift-Select Resource Grouping

---

console/src/ontology/Tree.tsx
pluto/src/tree/Tree.tsx

- **Linear Issue**: [SY-1936](https://linear.app/synnax/issue/SY-1936/fix-bad-expansion-and-contraction-behavior-in-ontology-tree)
We were incorrectly passing bad keys to the `contract` function on the ontology tree, which caused funky behavior with moving around expanded folders. This PR makes sure we pass in the right keys.

SY-1936 - Fix Bad Contraction Behavior in Ontology Tree

---

console/src/hardware/labjack/task/Read.tsx

- **Linear Issue**: [SY-2049](https://linear.app/synnax/issue/SY-2049)
Turns out the `overrideValidSchemas` implementation is totally fine, and it was an issue in the LabJack read task type change handler.

SY-2049 - Fix Labjack Port Override

---

console/src/layouts/GetStarted.tsx
console/src/layouts/Mosaic.tsx
console/src/layouts/Selector.tsx
console/src/lineplot/LinePlot.tsx
console/src/lineplot/layout.ts
console/src/lineplot/services/palette.tsx
console/src/log/Log.tsx
console/src/log/services/palette.tsx
console/src/schematic/Schematic.tsx
console/src/schematic/services/palette.tsx
console/src/selector/Selector.tsx
console/src/table/Table.tsx
console/src/table/services/palette.tsx
console/src/vis/Selector.tsx
console/src/vis/Toolbar.tsx

- **Linear Issue**: [SY-2093](https://linear.app/synnax/issue/SY-2093/workspace-failing-to-save-visualizations-on-reopen)
Made sure that when new visualizations are created in the console, the keys are all UUIDs. This prevents some issue where a workspace has a layout key that is not a UUID, so the workspace saves properly but the visualizations do not.

Fix Workspaces Failing to Save Visualizations from bad UUIDs

---

driver/sequence/plugins/channel_write.cpp
driver/sequence/plugins/channel_write_test.cpp
driver/sequence/plugins/plugins.h

- **Linear Issue**: [SY-2096](https://linear.app/synnax/issue/SY-2096)
Makes it so that when you attempt to make calls to `set` on a sequence with no channels in the `write_to` field, that an error is raised.

SY-2096 - Raise Error on Calls to Set With Empty `write_to` field

---

console/src/cluster/Dropdown.tsx
console/src/layout/slice.ts
console/src/layouts/Mosaic.tsx
console/src/layouts/nav/Top.tsx
console/src/palette/Palette.tsx
console/src/palette/Tooltip.tsx
console/src/palette/command.tsx
console/src/palette/resource.tsx
console/src/palette/types.ts
console/src/workspace/Selector.tsx
docs/site/src/components/feedback/Feedback.tsx
docs/site/src/components/search/Search.tsx
pluto/src/dialog/use.ts
pluto/src/dropdown/Dropdown.tsx
pluto/src/input/DateTime.tsx
pluto/src/select/Multiple.tsx
pluto/src/select/Single.tsx

- **Linear Issue**: [SY-1685](https://linear.app/synnax/issue/SY-1685/fix-palette-failing-to-switch-to-command-mode)
- Minor performance improvements to increase memoization in the Pluto Dialog.use hook
- Fix Quick Search & Command Palette mode switching

Fix Palette Switching and Update Pluto Dialog Hook

---

client/py/examples/dev/create_device.py
console/src/hardware/labjack/device/SelectPort.tsx
console/src/hardware/labjack/device/types.ts
console/src/hardware/labjack/task/OutputChannelForms.tsx
console/src/hardware/labjack/task/Read.tsx
console/src/hardware/labjack/task/Write.tsx
console/src/hardware/labjack/task/getOpenPort.spec.ts
console/src/hardware/labjack/task/getOpenPort.ts

- **Linear Issue**: [SY-2169](https://linear.app/synnax/issue/SY-2169/add-fio-ports-for-labjack-t4-analog-inputs)
Add in missing ports and port aliases for LabJack T4.

Fix LabJack T4 Ports

---

driver/ni/BUILD.bazel
driver/ni/scan_task.cpp
driver/ni/scan_task.h
driver/ni/scan_task_test.cpp

- **Linear Issue**: [SY-2180](https://linear.app/synnax/issue/SY-2180)
Fixes an issue where the NI scan task fails to ignore devices that should be ignored. Also adds regression tests.

SY-2180 - Fix NI Scan Task Ignore

---

client/ts/src/framer/adapter.spec.ts
console/src-tauri/tauri.conf.json
console/vite.config.ts
pluto/src/status/Aggregator.tsx
pluto/src/status/aether/aggregator.ts
pluto/src/vis/setpoint/aether/setpoint.ts
x/ts/src/telem/series.spec.ts
x/ts/src/telem/series.ts

- **Linear Issue**: [SY-2129](https://linear.app/synnax/issue/SY-2129)
Fixes a few important things:
- Fixes using setpoints with channels that require using bigints as their data.
- Modifies status aggregator to consolidate some code and add an async exception handler in aether.
- Makes the window default hidden to avoid blankscreening in tauri.

SY 2129 Fix BigInt Setpoints, Better Communicate Setpoint Errors, and Make Window Default Hidden

---

client/ts/src/framer/writer.ts
console/src/schematic/toolbar/Control.tsx
pluto/src/telem/control/Chip.tsx
pluto/src/telem/control/aether/chip.ts
pluto/src/telem/control/aether/controller.ts
x/ts/src/control/control.ts

- **Linear Issue**: [SY-2155](https://linear.app/synnax/issue/SY-2155)
Bounds the schematic control authority selector from 0 to 255.

SY-2155 - Bound Schematic Control Authority Selector

---

console/src/schematic/services/ontology.tsx

- **Linear Issue**: [SY-2172](https://linear.app/synnax/issue/SY-2172)
Disable copying schematic snapshot.

SY-2172 - Disable Copying Schematic Snapshot

---

freighter/go/fhttp/stream.go
freighter/go/fhttp/unary.go
freighter/go/fmock/unary.go
synnax/pkg/service/hardware/embedded/enabled.go

- **Linear Issue**: [SY-2179](https://linear.app/synnax/issue/SY-2179)
There are some strange implementation details related to fiber websockets. The fiber request context provided is only valid for the lifetime of the http request before we upgrade it to a websocket. We were mistakenly using the context past it's available lifetime. This fix makes it so that we use the underlying server context that is valid throughout the lifetime of the socket. Also makes changes to prevent these sorts of lifecycle mistakes in the future.

SY-2179 - Fix Shutdown Panic: Missing Cancel Error

---

console/src/hardware/ni/task/types/v0.ts
driver/labjack/read_task.h
driver/labjack/read_task_test.cpp
driver/ni/read_task.h
driver/ni/read_task_test.cpp
driver/ni/write_task.h
driver/ni/write_task_test.cpp
driver/opc/factory.cpp
driver/opc/read_task.h
driver/task/common/read_task.h
driver/task/common/read_task_test.cpp

- **Linear Issue**: [SY-2183](https://linear.app/synnax/issue/SY-2183)
Fixed missing channel types in Digital Input/Output channels in NI schemas, and made driver task parsing more resillient to unknown channel types.

SY-2183 - Fix Channel Null Pointers  When Configuring Read Tasks

---

console/src/layout/hooks.spec.tsx
console/src/layout/selectors.ts

- **Linear Issue**: [SY-2133](https://linear.app/synnax/issue/SY-2133)
Makes it so that triggers on mosaic windows do not work when a modal is focused.

SY-2133 - Fix Cmd+Enter in Configure Device Modals

---

console/src/hardware/labjack/task/InputChannelForms.tsx
console/src/hardware/labjack/task/Read.tsx
console/src/hardware/labjack/task/types.ts

- **Linear Issue**: [SY-2157](https://linear.app/synnax/issue/SY-2157/remove-max-voltage-field-from-labjack-read-task-thermocouple-channel)
Removed the max voltage field from the LabJack TC channel form as it is not used. Set
the default range to 10V instead of 0V.

SY-2157: Remove Max Voltage Field from LabJack Read Task Thermocouple Channels

---

client/ts/src/hardware/rack/payload.ts
client/ts/src/hardware/rack/rack.spec.ts
client/ts/src/hardware/task/task.spec.ts

- **Linear Issue**: [SY-2187](https://linear.app/synnax/issue/SY-2187)
Fixes an issue where a rack would just get re-created if you try to rename it. Also adds tests. 

SY - 2187 - Fix Rack Renaming

---

client/py/synnax/ranger/client.py
client/py/synnax/user/client.py
client/py/synnax/util/params.py
client/py/tests/test_ranger.py
docs/site/src/pages/reference/python-client/ranges.mdx

- **Linear Issue**: [SY-2188](https://linear.app/synnax/issue/SY-2188)
Current docs don't reflect the fact that `ranges.retrieve` requires you to pass in named parameters with `key` or `name`. This fixes the docs and improves the errors thrown. 

SY-2188 - Fix Named Parameter Convention in Range Docs

---

console/src/hardware/common/task/ChannelList.tsx
console/src/hardware/common/task/layouts/ChannelList.tsx
console/src/hardware/common/task/layouts/ListAndDetails.tsx

- **Linear Issue**: [SY-2160](https://linear.app/synnax/issue/SY-2160/add-duplicate-channels-to-task-channel-list-context-menu)
Added a "Duplicate Channel" to the context menu for NI Analog Read, NI Analog Write, and LabJack Read tasks.

SY-2160: Add Duplicate Channels to Task Channel List Context Menu

---

x/cpp/telem/series.h
x/cpp/telem/series_test.cpp

- **Linear Issue**: [SY-2194](https://linear.app/synnax/issue/SY-2194)
Fixed and added regression test for SampleValue at() with timestamps.

SY-2194 - Fix At() Support for Timestamps

---

console/package.json
console/src/hardware/opc/task/Read.tsx

- **Linear Issue**: [SY-2206](https://linear.app/synnax/issue/SY-2206/fix-opc-ua-task-renaming)
Make sure that configuring the OPC UA Read Task does not rename channels.

SY-2206: Fix OPC UA Read Task channel renaming

---

console/package.json
console/src/hardware/ni/task/types/types.spec.ts
console/src/hardware/ni/task/types/v0.ts
console/src/hardware/ni/task/types/v1.ts

- **Linear Issue**: [SY-2227](https://linear.app/synnax/issue/SY-2227/fix-ni-analog-input-task-multi-device-unique-port-validation)
Fixed an issue in the NI Analog Input task where channels with the same port number on different device were thought to not be unique ports.

SY-2226: Fix Unique Port Validation in NI Analog Input Task

---

console/package.json
console/src/hardware/opc/device/Connect.tsx
pluto/package.json
pluto/src/color/Swatch.tsx

- **Linear Issue**: [SY-2229](https://linear.app/synnax/issue/SY-2229)
Fix color swatch drag and drop and made it so you cannot clear the location when connecting an OPC UA server. 

SY-2229: Fixed Null Rack in OPC Connect & Color Swatch D&D

---

console/package.json
console/src/channel/Calculated.tsx
console/src/hardware/labjack/task/Read.tsx
console/src/hardware/labjack/task/Write.tsx
console/src/hardware/ni/task/AnalogRead.tsx
console/src/hardware/ni/task/AnalogWrite.tsx
console/src/hardware/ni/task/DigitalRead.tsx
console/src/hardware/ni/task/DigitalWrite.tsx

- **Linear Issue**: [SY-2237](https://linear.app/synnax/issue/SY-2237/fix-calculated-channels-serializing-bigints), [SY-2232](https://linear.app/synnax/issue/SY-2232/channels-being-recreated-ni-analog-read-task)
1. Make sure that opening existing calculated channels in the calculated channels modal does not cause an error by passing the channel class instead of the channel payload
2. Check that devices are configured before creating channels on them to avoid the _ai_0 names.

Update console bugs

---

console/src/hardware/common/device/checkConfigured.ts
console/src/hardware/labjack/task/Read.tsx
console/src/hardware/labjack/task/Write.tsx
console/src/hardware/ni/task/AnalogRead.tsx
console/src/hardware/ni/task/AnalogWrite.tsx
console/src/hardware/ni/task/DigitalRead.tsx
console/src/hardware/ni/task/DigitalWrite.tsx

- **Linear Issue**: [SY-2238](https://linear.app/synnax/issue/SY-2238/standardize-device-is-not-configured-errors)
Standardize code for "Device is not configured" error.

Standardize "Device is not configured" error

---

console/src/code/Editor.css

- **Linear Issue**: [SY-2307](https://linear.app/synnax/issue/SY-2307)
Using geist mono for editor font on windows caused cursor offset problems. This is a temporary fix to just switch back to default font.

SY-2307: Temporarily Use Default Font In Code Editor on Windows

---

console/src/hardware/task/sequence/globals.ts

- **Linear Issue**: [SY-2303](https://linear.app/synnax/issue/SY-2303/add-set-authority-to-control-sequence-editor-global-variables)
Add set_authority to the global variables in the console for control sequences.

Add set_authority to control sequence editor global variables

---

console/src/table/Toolbar.tsx

- **Linear Issue**: [SY-2270](https://linear.app/synnax/issue/SY-2270/fix-table-cell-selection-in-console)
Trigger a unmount->mount of the table toolbar whenever a different cell is selected. This is to prevent an issue where two different cells with the same property were selected consecutively, and then changing the cell type from value to text would change the previously selected cell's value instead of the current one.

Trigger unmount / mount of table toolbar for different cells.

---

pluto/src/vis/text/atlas.ts

…tlas
- **Linear Issue**: [SY-2472](https://linear.app/synnax/issue/SY-2472)

SY-2472 - Fix Display of Scientific and Exponential Engineering Units with Text Atlas

---

console/src/cluster/Connect.tsx
pluto/src/form/Form.tsx
x/ts/src/zod/util.spec.ts

- **Linear Issue**: [SY-2467](https://linear.app/synnax/issue/SY-2467)

SY-2467 - Fix Optional Field Checks in Pluto Forms

---

console/src/channel/Calculated.tsx

- **Linear Issue**: [SY-2480](https://linear.app/synnax/issue/SY-2480)

SY-2480 - Fixed Auto-Complete of 'get' In Calculated Channels

---

pluto/src/telem/aether/remote.spec.ts
pluto/src/telem/aether/remote.ts

- **Linear Issue**: [SY-2481](https://linear.app/synnax/issue/SY-2481)

SY-2481 - Fix Pluto Telem Backloading of Calculated Channels in Streaming Scenarios

---

client/py/pyproject.toml
client/py/synnax/hardware/opcua/types.py
client/py/synnax/hardware/task/client.py
client/py/tests/test_opcua.py

[SY-2526](https://linear.app/synnax/issue/SY-2526/actually-fix-opc-ua-read-task-pydantic-model-validation)
Actually fix the opc ua read task pydantic model validation when retrieving a task

Sy-2526-actually-fix-opc-ua-read-task-pydantic-model-validation

---

pluto/src/align/Pack.tsx
pluto/src/button/Button.tsx
pluto/src/dropdown/Dropdown.tsx
pluto/src/tooltip/Dialog.css
pluto/src/tooltip/Dialog.tsx
pluto/src/tree/Tree.tsx
pluto/src/vis/schematic/primitives/Primitives.tsx

[SY-2426](https://linear.app/synnax/issue/SY-2525/fix-expect-error-on-css-variables)
Getting some nasty issues by blatantly ignoring an entire line of TS code when using CSS variables. This fixes that issue by using spread operators and `as CSSProperties` where necessary. 
Read through this stack overflow thread and didn't find anything particularly ideal, so just went a more standard route: https://stackoverflow.com/questions/52005083/how-to-define-css-variables-in-style-attribute-in-react-and-typescript

Remove TS-Expect-Error from CSS Variable Typing

---

pluto/src/vis/draw2d/canvas.ts
pluto/src/vis/text/atlas.ts

[SY-2538](https://linear.app/synnax/issue/SY-2527/center-text-in-schematic-values)
Fixes issues with centering in text atlas. Turns out that DPI doesn't matter if we just upscale the atlas canvas.

SY-2527 - Center Text In Schematic Valus

---

console/src/channel/services/ontology.tsx

[SY-1185](https://linear.app/synnax/issue/SY-1185/hide-remove-alias-menu-option-when-no-alias-exists)

SY-1185: Hide remove alias menu option when no alias exists

---

synnax/pkg/distribution/cluster/ontology.go

[SY-2585](https://linear.app/synnax/issue/SY-2585/check-for-cluster-ontology-service-deadlock-potential)
Remove a potential deadlock in the cluster ontology service.

SY-2585: Remove potential deadlock in cluster ontology service

---

console/src/hardware/ni/task/AnalogRead.tsx
console/src/hardware/ni/task/AnalogWrite.tsx
console/src/hardware/ni/task/SelectAIChannelTypeField.tsx
console/src/hardware/ni/task/SelectAOChannelTypeField.tsx
console/src/hardware/ni/task/types/v0.tsx

[SY-2550](https://linear.app/synnax/issue/SY-2550/match-icon-color-in-ni-analog-tasks)
Match icon colors in NI analog read and write tasks.

SY-2550: Match icon color in NI analog tasks

---

client/py/synnax/status/status.py

[SY-2651](https://linear.app/synnax/issue/SY-2651/remove-python-313-syntax-from-python-client)
Remove the Python 3.13 syntax of the `default` arg in `TypeVar`. Also fixed the default initialization of `time` and `key` to be dynamically generated.

SY-2651: Remove Python 3.13 Syntax and fix default status initialization

---

docs/site/src/components/Diagram.astro
docs/site/src/components/NextPrev.astro
docs/site/src/components/Rule.astro
docs/site/src/components/Table.tsx
docs/site/src/components/details/Summary.astro
docs/site/src/components/mdxOverrides.tsx
docs/site/src/components/releases/Release.astro
docs/site/src/middleware.ts
docs/site/src/pages/guides/comparison/performance/one-billion-rows/index.mdx
docs/site/src/pages/guides/operations/automated-control.mdx
docs/site/src/pages/reference/python-client/device-driver.mdx
docs/site/src/pages/releases/Thumbnail0370.astro

[SY-1845](https://linear.app/synnax/issue/SY-1845/fix-dropdown-code-on-documentation-site)
- Fix some Astro linting issues with the documentation site
- Remove the custom `<Summary />` component

SY-1845: Fix Summary & Details Code on Documentation Site

---

client/py/examples/control/abort/nominal_sequence.py

[SY-2716](https://linear.app/synnax/issue/SY-2716/rename-the-name-of-the-nominal-sequence-from-press-sequence-to-nominal)
Rename the name of the nominal sequence in the abort example.

SY-2716: Rename the name of the nominal sequence in abort example

---

pluto/src/dialog/Frame.tsx
pluto/src/menu/ContextMenu.tsx

[SY-2681](https://linear.app/synnax/issue/SY-2681/prevent-clicking-outside-context-menu-from-closing-dropdown-dialogs)
Clicking on a context menu that was opened inside of a dropdown (such as cluster select) would result in the dialog being closed if the button on the context menu was outside of the dropdown. This fixes that issue.

SY-2681 -  Exclude Context Menus from Closing Dropdowns

---

client/py/poetry.lock
client/py/pyproject.toml

[SY-2795](https://linear.app/synnax/issue/SY-2795/add-matplotlib-to-client-dependencies-or-remove-requirement)
Move Matplotlib to a direct dependency of the Python client library.

SY-2795: Move Matplotlib to direct client dependency

---

synnax/pkg/service/framer/calculation/calculator.go
synnax/pkg/service/framer/calculation/calculator_test.go
synnax/pkg/service/framer/calculation/service.go

[SY-2788](https://linear.app/synnax/issue/SY-2788/fix-calculated-channel-server-panic)
Fixes an issue where calculated channels whose series crossed domains would result in a panic.

SY-2788 - Fixed Calculated Channels Across Domains

---

pluto/src/telem/aether/remote.spec.ts

[SY-2743](https://linear.app/synnax/issue/SY-2743/add-staleness-to-schematic-values)
remote.ts now returns NaN when a channel primitive isZero, the leading buffer is null, or the leading buffer length is 0. remote.spec.ts must be updated.

Update Unit Tests for expected NaN values

---

console/src/hardware/common/task/types.ts
console/src/hardware/labjack/task/types.spec.ts
console/src/hardware/labjack/task/types.ts
console/src/hardware/ni/task/types/v0.tsx
console/src/hardware/opc/task/Write.tsx
console/src/hardware/opc/task/types.spec.ts
console/src/hardware/opc/task/types.ts

[SY-2885](https://linear.app/synnax/issue/SY-2885/remove-data-saving-from-opc-write-field)
Remove `dataSaving` from OPC UA Write Task Form.

SY-2885: Remove `dataSaving` from OPC UA Write Task

---

console/src/hardware/ni/task/DigitalRead.tsx
console/src/hardware/opc/task/Form.tsx

[SY-2879](https://linear.app/synnax/issue/SY-2879/make-channel-names-bigger-on-opc-read-task)
Improve channel name sizing in NI Digital Read and OPC UA Tasks.

SY-2879: Improve sizing of channel names in task forms

---

console/src/schematic/toolbar/Symbols.tsx
core/pkg/api/schematic.go
core/pkg/service/workspace/schematic/symbol/retrieve.go
core/pkg/service/workspace/schematic/symbol/service.go
pluto/src/schematic/symbol/queries.ts

[SY-2860](https://linear.app/synnax/issue/SY-2860/search-symbols-in-schematic-toolbar-should-search-across-groups)

SY-2860 - Fix Remote Search In Schematic Symbols Toolbar

---

console/src/schematic/services/palette.tsx

[SY-2849](https://linear.app/synnax/issue/SY-2849/remove-schematic-symbol-from-command-palette)
Remove the create schematic symbol command from the command palette.

SY-2849: Remove "Create Symbol" command from command palette

---

console/src/schematic/symbols/useDeleteSymbolGroup.ts
console/src/schematic/toolbar/Symbols.tsx

[SY-2855](https://linear.app/synnax/issue/SY-2855/escaping-out-of-the-delete-symbol-group-pop-up-deletes-the-symbol)
Fix an error where escaping from the symbol group deletion modal still caused the group to be deleted.

SY-2855: Fix Symbol Group Deletion Modal

---

console/src/hardware/common/task/Form.tsx

[SY-2879](https://linear.app/synnax/issue/SY-2878/drag-and-drop-import-of-ni-digital-read-task-does-not-allow-for)
Fix the drag and drop import of tasks.

SY-2879: Fix drag and drop import of tasks

---

console/src/hardware/task/sequence/Sequence.tsx
console/src/hardware/task/sequence/types.ts

[SY-2861](https://linear.app/synnax/issue/SY-2861/control-sequence-does-not-require-a-deployment-location)
Make the device location required for a control sequence schema.

SY-2861: Make device location required in control sequence

---

console/src/range/services/link.ts

[SY-2893](https://linear.app/synnax/issue/SY-2893/fix-layout-name-sync-problems-when-opening-ranges)
Fix placing the range overview layout name from the link.

SY-2893: Fix placing range overview layout from link

---

console/src/schematic/symbols/edit/RegionList.tsx
pluto/src/color/Swatch.css

[SY-2840](https://linear.app/synnax/issue/SY-2840/add-tooltips-to-stroke-and-fill-color-symbols-on-schematic-symbol)

SY-2840 - Add Tooltips To Stroke and Fill Icons on Schematic Symbol Edit Dialog

---

pluto/src/form/Context.spec.tsx
pluto/src/form/Context.ts
pluto/src/form/Field.tsx
pluto/src/form/useField.ts
pluto/src/hooks/useRequiredContext.spec.tsx
pluto/src/hooks/useRequiredContext.ts

[SY-2936](https://linear.app/synnax/issue/SY-2936/fix-form-context)
Makes it so that calls to `Form.useContext()` no longer return a zero value and instead now throw an error. Also added tests that error messages are actually good.

SY-2936: Improve Form Context Handling

---

pluto/src/flux/list.spec.ts
pluto/src/flux/list.ts
pluto/src/form/Context.spec.tsx

[SY-2947](https://linear.app/synnax/issue/SY-2947/flux-make-it-so-that-key-based-retrieves-do-not-retrieve-on-zero)
See comment on non-test diff for explanation of this change.

SY-2947: Add Primitive Zero Handling Check to Flux List Get Item

---

console/package.json
console/src/schematic/slice.ts

[SY-2949](https://linear.app/synnax/issue/SY-2949/hotfix-schematic-undoredo)
Schematic undo and redo were broken due to a readonly assigment. This problem is now fixed.

SY-2949 - Hotfix Schematic Undo/Redo

---

freighter/go/falamos/falamos.go
freighter/go/fhttp/stream.go

[SY-2954](https://linear.app/synnax/issue/SY-2954/skip-logging-of-certain-websocket-close-errors)
Reduces useless API/transport logging that hides actual issues and causes unnecessary concerns with customers.

SY-2954: Api/Freighter - Skip Logging of Certain Websocket Close Errors and context.Canceled Errors

---

console/src/hardware/common/task/layouts/ChannelList.tsx
console/src/hardware/ni/task/DigitalChannelList.tsx
console/src/hardware/ni/task/DigitalRead.tsx
console/src/hardware/ni/task/DigitalWrite.tsx
pluto/src/hardware/rack/Select.tsx
pluto/src/label/Select.tsx
pluto/src/text/Editable.tsx

[SY-2881](https://linear.app/synnax/issue/SY-2881/cannot-rename-opc-ua-server-channel)
1. Fix the `Layouts.ChannelList` component to properly pass props into child components.
2. Use browser-implemented `CSS.escape` instead of custom `escapeCharacters` function in `Text.Editable`.
3. Stop passing key into the name components for NI Digital tasks and instead use itemKey.

SY-2881: Fix Renaming Channels in Tasks

---

core/pkg/service/hardware/rack/rack_test.go
core/pkg/service/hardware/rack/service.go
core/pkg/service/hardware/rack/writer.go
core/pkg/service/hardware/task/task_test.go
core/pkg/service/hardware/task/writer.go

[SY-2967](https://linear.app/synnax/issue/SY-2967/fix-task-key-assignment-race)
Fixes an issue where task keys generated concurrently wouldn't actually be in succession because they were using open transactions instead of writing directly to the underlying key-value database.

SY-2967: Fix Task Key Generation Race

---

configs/eslint/index.js
console/src/label/Edit.tsx
console/src/range/overview/Details.tsx
console/src/range/overview/MetaData.tsx
console/src/schematic/symbols/edit/Edit.tsx
docs/site/src/components/search/Search.tsx
pluto/src/button/Button.spec.tsx
pluto/src/input/Input.spec.tsx
pluto/src/select/Single.spec.tsx
pluto/src/showcase/InputShowcase.tsx
pluto/src/triggers/Triggers.spec.tsx

[SY-2982](https://linear.app/synnax/issue/SY-2982/add-react-eslint-rules-for-string-and-boolean-props-style)
Add two ESLint rules to enforce style consistency in React code.

SY-2982: Add`react/jsx-curly-brace-presence` and `react/jsx-boolean-value` ESLint rules

---

console/src/lineplot/LinePlot.tsx

[SY-2998](https://linear.app/synnax/issue/SY-2998/fix-dividers-on-line-plot-selection-context-menu)
remove an extra divider on the line plot selection context menu

SY-2998: Remove extra Divider on Line Plot Selection Context Menu

---

console/src/channel/services/ontology.tsx
console/src/hardware/rack/ontology.tsx
console/src/ontology/service.tsx
console/src/range/services/external.ts
console/src/range/services/ontology.tsx
console/src/services.ts
core/pkg/service/layer.go

[SY-2993](https://linear.app/synnax/issue/SY-2993/remove-groups-from-search-palette)
Remove racks, nodes, and other items that can't be selected from the search palette. Add back in the range item that got deleted in the range PR.

SY-2993: Clean up Search Palette Items

---

client/ts/src/hardware/task/client.ts
client/ts/src/hardware/task/task.spec.ts
console/src/hardware/task/Toolbar.tsx
core/pkg/api/hardware.go
core/pkg/service/hardware/task/retrieve.go
core/pkg/service/hardware/task/task_test.go
pluto/src/hardware/task/queries.ts

[SY-3100](https://linear.app/synnax/issue/SY-3100/fix-task-channel-name-loading-issues)
Hotfixes the number of list items displayed in the task toolbar, and properly remote filters internal and snapshot tasks. One of the notable things is the `1000` list item limit in the task toolbar. This is a temp fix and will eventually need to be addressed.

SY-3103: Fixed Task Toolbar Retrieval
