deploy/Dockerfile
deploy/README.md
deploy/deployment.py
deploy/poetry.lock
deploy/pyproject.toml
deploy/requirements.txt

This PR addresses issue #355 by providing a Docker-based lifecycle management solution to synnax.

[deployer] - Impl Synnax Deployer, resolves #355

---

docs/site/src/components/Media.tsx
docs/site/src/layouts/MainLayout.astro
docs/site/src/pages/console/connect-a-cluster.mdx
docs/site/src/pages/console/nav.tsx
docs/site/src/pages/console/pid.mdx

Push for the PID view

---

client/ts/examples/node/basicReadWrite.js
client/ts/examples/node/package-lock.json
docs/site/src/pages/reference/typescript-client/write-data.mdx

- [SY-767](https://linear.app/synnaxlabs/issue/SY-767/[docs]-improve-referencets-clientwrite-data)
Accurate reference for writing data with typescript client. also changed minor things in example
with necessary manual QA steps to test my change. - **N/A**

[docs] - improvements to ts write reference

---

console/src/channel/Create.tsx
console/src/hardware/ni/device/Configure.css
console/src/hardware/opc/device/Configure.css
console/src/hardware/opc/device/Configure.tsx
console/src/hardware/opc/device/CreateChannels.tsx
console/src/hardware/opc/task/ReadTask.tsx
console/src/palette/Palette.tsx
console/src/range/Toolbar.tsx
pluto/src/form/Form.tsx

- Linear Issue: Addresses [SY-901](https://linear.app/synnaxlabs/issue/SY-901/vanishing-channels-in-opc-ua-server-setup) and  [SY-899](https://linear.app/synnaxlabs/issue/SY-899/erroneous-error-message-in-opc-read-task)
Fixes vanishing channels in OPC UA server configuration dialog and incorrect path validation in OPC read task.

Sy 901 vanishing channels in opc ua server setup

---

docs/site/package.json
pluto/src/tree/Tree.css
pluto/src/tree/Tree.tsx

- **Linear Issue**: [SY-931](https://linear.app/synnaxlabs/issue/SY-931/fix-vercel-docs-deploy)
Fixes deployment of the documentation site to vercel by removing an unnecessary postbuild 

Fixed vercel docs build

---

pluto/src/dropdown/Dropdown.tsx

- **Linear Issue**: [SY-932](https://linear.app/synnaxlabs/issue/SY-932/sticky-dropdown-positioning)
Makes it so that when a user opens a dropdown and it opens in a particular direction, it prefers the same direction for future renders. This makes it so the dropdown doesn't 'flip flop' sides.
N/A

[console] - implemented sticky dropdown positioning

---

.github/PULL_REQUEST_TEMPLATE/rc.md

- **Linear Issue**: [SY-955](https://linear.app/synnaxlabs/issue/SY-955/console-qa-process-review)
Edited the QA review process for the console to cover more scope.

Edited Console QA Process

---

client/py/synnax/framer/writer.py
client/py/tests/test_framer.py
client/ts/src/framer/writer.spec.ts

- **Linear Issue**: [SY-962](https://linear.app/synnaxlabs/issue/SY-962/[py-and-ts-client]-add-tests-for-setauthority)
We are using the setauthority feature but there are no tests for it. This PR adds the appropriate test cases. In developing this PR, I uncovered a [bug](https://linear.app/synnaxlabs/issue/SY-965/[py-client]-rate-channel-write-dropping-samples) regarding python client writing to rate channels.

[client] - added setAuthority test cases

---

synnax/pkg/api/api.go
x/go/httputil/encoder.go

- **Linear Issue**: [SY-976](https://linear.app/synnaxlabs/issue/SY-976/[server]-make-connectivity-insecure-api)
Made the connectivity endpoint of the server API insecure.

Sy 976 server make connectivity insecure api

---

synnax/pkg/distribution/framer/iterator/iterator_suite_test.go
synnax/pkg/distribution/framer/iterator/iterator_test.go
synnax/pkg/distribution/framer/iterator/server.go

- **Linear Issue**: [SY-966](https://linear.app/synnaxlabs/issue/SY-966/[server]-iterator-tests)
Added test cases for iterator + fixed a bug that caused iterators on peer nodes to panic.

[server] - added test cases for iterator

---

synnax/pkg/distribution/channel/verification/service.go
synnax/pkg/distribution/channel/verification/verification.go

- **Linear Issue**: [SY-997](https://linear.app/synnaxlabs/issue/SY-997/license-key-logs)
Improved logging messages.

Improved log messages

---

driver/vendor/open62541/build_macos.sh

- **Linear Issue**: [SY-10009](https://linear.app/synnaxlabs/issue/SY-1009/upgrade-open62541-version)
Maximum 2-3 sentence description describing the changes.

[driver/opcua] - updated open62541 version

---

console/src/range/Toolbar.tsx
console/src/range/migrations/index.ts
console/src/range/migrations/v0.ts
console/src/range/selectors.ts
console/src/range/services/external.ts
console/src/range/services/index.ts
console/src/range/services/link.tsx
console/src/range/services/ontology.tsx

- **Linear Issue**: [SY-895](https://linear.app/synnaxlabs/issue/SY-895/remove-range-from-toolbar-when-deleting-from-resources)
When deleting a range from the resources toolbar, also delete the range from the store. Also some formatting changes in `console/src/range`.

Remove Range from Range Toolbar when Deleting from Resource Toolbar

---

.github/workflows/test.console.yaml
console/package.json
package.json
pnpm-lock.yaml

- **Linear Issue**: [SY-930](https://linear.app/synnaxlabs/issue/SY-930/[console]-add-console-tests-to-release-ci)
Added console tests to CI

SY-930 add console tests to ci

---

.github/PULL_REQUEST_TEMPLATE/rc.md
console/package.json
console/src/channel/Create.tsx

- **Linear Issue**: [SY-1111](sy-1111-console-crashes-when-create-more-is-true-on-channel-creation)
Fixes a critical issue where choosing "Create More" when creating a channel would cause the console to crash. 

[console] - fixed virtual channel create more bug

---

console/src/label/Edit.tsx

- **Linear Issue**: [SY-1081](https://linear.app/synnax/issue/SY-1081/[console]-improve-default-label-colors)
Changed default label colors so that each new label is a new color.

SY-1081 Add extra default label color

---

.github/workflows/api.client.yaml
client/ts/api/client.api.md

This PR changes the client API GitHub action to pass when there are API changes in the base branch.

SY-1096 Update Client API GitHub Action to Pass on Back Merges

---

.github/PULL_REQUEST_TEMPLATE/rc.md
console/src/channel/services/ontology.tsx
console/src/hardware/device/ontology.tsx
console/src/hardware/task/ontology.tsx
console/src/layout/Modals.tsx
console/src/schematic/services/ontology.tsx
console/vite.config.ts
pluto/src/modal/Modal.css
x/media/src/Icon/Icon.css
x/media/src/Icon/index.tsx

- **Linear Issue**: [SY-1125](https://linear.app/synnax/issue/SY-1125/grouping-devices-does-not-work)
Fixed an issue where grouping devices and tasks would not work. 

SY-1225 - Grouping devices does not work

---

console/src/channel/Create.tsx
console/src/cluster/Connect.css
console/src/cluster/Connect.tsx
console/src/confirm/Confirm.tsx
console/src/hardware/opc/device/Configure.tsx
console/src/layout/Modals.css
console/src/layout/Modals.tsx
console/src/range/EditLayout.tsx
console/src/workspace/Create.tsx
pluto/src/modal/Modal.tsx

- **Linear Issue**: [SY-1131](https://linear.app/synnax/issue/SY-1131/improve-padding-symmetry-on-modal-toolbar)
Standardizes the padding across modal bottom nav bars and makes it more symmetrical.

SY-1311 - improved modal bottom nav bars

---

docs/site/src/pages/reference/control/sequence-basics.mdx

- **Linear Issue**: [SY-1169](https://linear.app/synnax/issue/SY-1169/hotfix-control-sequence-docs)
Fixes wrong arguments in control sequence basics documentation.

[docs/site] - hotfixed controller arguments

---

client/py/examples/control/abort/README.md
docs/site/src/components/console/OSDownloadButton.tsx
docs/site/src/pages/reference/console/_nav.tsx
docs/site/src/pages/reference/console/channels.mdx
docs/site/src/pages/reference/console/line-plots.mdx
docs/site/src/pages/reference/console/schematics.mdx
docs/site/src/pages/reference/control/_nav.tsx
docs/site/src/pages/reference/control/examples.mdx
docs/site/src/pages/reference/python-client/examples.mdx
pluto/src/triggers/Text.tsx

Minor changes to the documentation for Synnax v0.28:
- Remove Linux from Console download button
- Add control sequence example page to docs
- Add channel page in console
- Section on snapshotting a schematic

SY-1155 Synnax v0.28 Documentation Update

---

docs/site/src/pages/reference/cluster/cli-reference.mdx

- **Linear Issue**: [SY-1198](https://linear.app/synnax/issue/SY-1198/update-cli-reference-with-driver-flags) 
Updates docs with missing documentation about driver specific flags for server cli.

SY 1198 Add driver flags to CLI Docs

---

console/package.json
pluto/package.json
pluto/src/button/Button.css
pluto/src/button/Button.tsx

- **Linear Issue**: [SY-1190](https://linear.app/synnax/issue/SY-1190/fix-primary-button-color)
Fixes bad text color on primary button in light mode.
Maximum 2-3 sentence description describing the changes.

[pluto] - adjusted primary button CSS style

---

.github/PULL_REQUEST_TEMPLATE/rc.md
console/src/lineplot/LinePlot.tsx
console/src/range/EditLayout.css
console/src/range/EditLayout.tsx
console/src/range/Select.tsx
console/src/range/Toolbar.tsx
console/src/range/external.ts
console/src/range/overview/ChildRanges.tsx
console/src/range/services/ontology.tsx
console/src/range/services/palette.tsx

Reverts synnaxlabs/synnax#803 - should not have pushed to main.

Revert "SY-1141 Remove Edit Range from Create Range Modal"

---

client/py/synnax/control/controller.py
client/py/tests/test_control.py
docs/site/src/pages/reference/concepts/writes.mdx
docs/site/src/pages/reference/control/sequence-basics.mdx
pluto/src/note/Note.css

- **Linear Issue**: [SY-1216](https://linear.app/synnax/issue/SY-1216/document-new-controller-wait-conditions)
Changes the `while_true` method to `wait_while` and adds documentation for the `wait_while` method and `remains_true_for` method. Also makes a minor CSS change to the `Note` component.

Sy 1216 document new controller wait conditions

---

console/src/layout/slice.ts

Revert "Sy 1159 schematic cannot get edited on windows"

---

console/package.json
console/src/hardware/opc/device/Configure.tsx
console/src/hardware/opc/device/ontology.tsx

- **Linear Issue**: [SY-1297](https://linear.app/synnax/issue/SY-1297/make-it-possible-to-edit-opc-ua-connection-parameters)
Makes it possible to edit OPC UA connection parameters.

[console] - made it possible to edit OPC UA server connection parameters

---

console/package.json
pluto/src/dropdown/Dropdown.tsx

- **Linear Issue**: [SY-1314](https://linear.app/synnax/issue/SY-1314/fix-ddown-pos)
Maximum 2-3 sentence description describing the changes.

[pluto] - fixed dropdown positioning on windows

---

client/ts/src/framer/frame.spec.ts
client/ts/src/framer/frame.ts
client/ts/src/framer/writer.ts
x/ts/src/telem/gl.ts
x/ts/src/telem/series.spec.ts
x/ts/src/telem/series.ts
x/ts/src/zodutil/zodutil.ts

- **Linear Issue**: [SY-1331](https://linear.app/synnax/issue/SY-1331/dead-streamer-in-line-plot)
Fixes an issue where a series with length zero does not get parsed correctly.

SY-1331 Fixed Issues with Streamer Parsing in Zod

---

docs/site/src/components/search/Search.tsx
pluto/src/align/Space.css

- **Linear Issue**: [SY-1345](https://linear.app/synnax/issue/SY-1345/fix-border-color-in-documentation-site)
Fixes an issue where the border color on the nav and search bar did not appear correctly on the latest version of Synnax.

[docs/site] - fixed issues with border color

---

console/src/hardware/device/ontology.tsx
console/src/hardware/ni/task/common.tsx
console/src/hardware/opc/task/ReadTask.tsx
console/src/hardware/opc/task/WriteTask.tsx
console/src/hardware/task/external.ts
console/src/hardware/task/link.ts
console/src/hardware/task/ontology.tsx
console/src/layouts/Main.tsx
console/src/link/link.tsx

- **Linear Issue**: [SY-1296](hhttps://linear.app/synnax/issue/SY-1296/deep-linking-for-tasks)
Added deep linking for tasks. Removed the copy link to clipboard from the device ontology menu.

SY-1296 Task Deep Linking

---

console/src/hardware/task/Toolbar.tsx

- **Linear Issue**: [SY-946](https://linear.app/synnax/issue/SY-946/open-task-from-task-toolbar)
This reformats the context menu in the task toolbar and allows for the task page to be opened from the toolbar.

SY-946: Open Task from Task Toolbar

---

.github/workflows/deploy.console.yaml

- **Linear Issue**: [SY-1186](https://linear.app/synnax/issue/SY-1186/macos-accessibility-access-prompt)
Updates console CI to add signing and notarization by apple, fixing issues with the accessibility prompt on MacOS.

Sy 1186 Fix MacOS Accesibility Prompt by Signing Application

---

pluto/src/vis/line/aether/line.ts
pluto/src/vis/value/aether/value.ts

- **Linear Issue**: [SY-#](https://linear.app/synnax/issue/)
Please write a short (2-3 sentence) description describing the changes.

Sy 1361 fix excessive value re rendering

---

docs/site/src/pages/reference/console/_nav.tsx
docs/site/src/pages/reference/console/schematics.mdx
docs/site/src/pages/reference/console/users.mdx

- **Linear Issue**: [SY-1249](https://linear.app/synnax/issue/SY-1249/access-control-and-user-registration-documentation)
Add a documentation page on user registration and access control.

SY-1249: User Registration and Access Control Documentation

---

docs/site/src/components/Footer.astro
docs/site/src/pages/privacy-policy.astro

- **Linear Issue**: [GTM-61](https://linear.app/synnax/issue/GTM-61/website-privacy-policy)
Adds a privacy policy to the documentation site. Will update the landing page after this is approved.

GTM-61 - Added privacy policy to documentation site

---

WORKSPACE

- **Linear Issue**: [SY-1417](https://linear.app/synnax/issue/1417)
Update mbedtls to 3.6.2

Sy 1417 update mbedtls to 3.6.2 on mac

---

docs/site/src/pages/reference/device-drivers/labjack/configure-device.mdx
docs/site/src/pages/reference/device-drivers/labjack/get-started.mdx
docs/site/src/pages/reference/device-drivers/labjack/read-task.mdx
docs/site/src/pages/reference/device-drivers/labjack/write-task.mdx
docs/site/src/pages/reference/device-drivers/ni/configure-device.mdx
pluto/src/tree/Tree.css

- **Linear Issue**: [SY-1433](https://linear.app/synnax/issue/SY-1433/hotfix-labjack-docs)
Fixes some minor typos and CSS styles in LabJack documentation.

[docs/site] - fixed typos and minor issues in LabJack documentation

---

console/src-tauri/gen/schemas/windows-schema.json
console/src/hardware/task/common/common.css
pluto/src/dropdown/Dropdown.tsx

- **Linear Issue**: [SY-1446](https://linear.app/synnax/issue/SY-1446/fix-task-flashing)
Fixes issues with CSS container queries that causes certain Modal components to flash.

[console] - fixed issues with task dialog flashing

---

console/src-tauri/gen/schemas/windows-schema.json
console/src/hardware/task/common/common.css
console/src/layout/Content.tsx
console/src/layout/Window.tsx
console/src/layout/hooks.ts
console/src/layout/middleware.ts
console/src/layout/selectors.ts
console/src/layout/slice.ts
console/src/layouts/Mosaic.tsx
console/src/middleware.ts
console/src/store.ts
console/src/vis/Canvas.tsx
drift/src/selectors.ts
pluto/src/dropdown/Dropdown.tsx

- **Linear Issue**: [SY-#](https://linear.app/synnax/issue/)
Please write a short (2-3 sentence) description describing the changes.

Sy 1461 fix issues with improper window shutdown throwing errors

---

console/package.json
console/src/layout/selectors.ts

- **Linear Issue**: [SY-#](https://linear.app/synnax/issue/)
Please write a short (2-3 sentence) description describing the changes.

[console] - adjusted layout selectors to show Mosaic window correctly

---

console/src-tauri/tauri.conf.json

- **Linear Issue**: No issue
Update the `$schema` field in `console/src-tauri/tauri-conf-json`.

ops(console): Update `tauri.conf.json` schema

---

console/package.json
console/src/lineplot/migrations/v2.ts
console/src/ontology/Tree.tsx
pluto/package.json
pluto/src/tree/core.ts
pluto/src/vis/diagram/Diagram.css
pluto/src/vis/lineplot/aether/YAxis.ts
pluto/src/vis/schematic/Forms.tsx
pluto/src/vis/schematic/Symbols.tsx
pluto/src/vis/schematic/primitives/Primitives.tsx
pluto/src/vis/schematic/registry.ts

Synnax v0.34.1

---

docs/site/src/pages/releases/0-35-0.mdx
docs/site/src/pages/releases/index.mdx

- **Linear Issue**: [SY-1531](https://linear.app/synnax/issue/1531)

SY 1531 v0.35 release notes

---

.github/workflows/deploy.console.yaml

- **Linear Issue**: [SY-1620](https://linear.app/synnax/issue/SY-1620/fic-console-auto-updater-on-mac)
Fixed auto update on MacOS.

[console] - fixed auto update on macos

---

console/src/hardware/labjack/task/Write.tsx

- **Linear Issue**: [SY-1619](https://linear.app/synnax/issue/SY-1619/fix-labjack-write-task-spacing)
Fixed the spacing in the LabJack Write Task channel details form.

fix(console): Fix LabJack Write Task Spacing

---

docs/site/src/pages/guides/sys-admin/_nav.tsx
docs/site/src/pages/guides/sys-admin/multiple-users.mdx

- **Linear Issue**: [SY-1605](https://linear.app/synnax/issue/SY-1605/multiple-user-registration-guide)
Added a guide for using Synnax with multiple users.

SY-1605: Multiple User Registration Guide

---

console/src/schematic/slice.ts
pluto/src/vis/schematic/Forms.tsx
pluto/src/vis/schematic/Symbols.tsx
pluto/src/vis/schematic/primitives/Primitives.tsx
pluto/src/vis/schematic/registry.ts

Sy 1604 clickable manual valves

---

.github/workflows/deploy.console.yaml
console/package.json
console/src/hardware/labjack/task/Write.tsx
console/src/schematic/slice.ts
docs/site/src/pages/reference/console/line-plots.mdx
docs/site/src/pages/reference/console/logs.mdx
docs/site/src/pages/reference/console/schematics.mdx
docs/site/src/pages/reference/console/tables.mdx
docs/site/src/pages/reference/console/workspaces.mdx
drift/package.json
drift/src/tauri/index.ts
pluto/package.json
pluto/src/breadcrumb/Breadcrumb.tsx
pluto/src/vis/schematic/Forms.tsx
pluto/src/vis/schematic/Symbols.tsx
pluto/src/vis/schematic/primitives/Primitives.tsx
pluto/src/vis/schematic/registry.ts

* docs(console): formatting and spelling fixes
* docs(console): add information about workspaces not saving visualizations
- **Version Number**: 
I have verified that the following files have the same minor version number:
I have verified that, when released, the following packages will not conflict with any previously released packages:
I have verified that user-facing documentation for each of the following services has been updated to match any changes in the release candidate:
I have verified that code examples for each of the following services run correctly:
I can successfully:
- **Create Channel Modal**
- **Resources Toolbar**
- **Context Menu**
- **Search and Command Palette**
- Resources Toolbar
- Line Plot Visualization Toolbar
- Log Visualization Toolbar
- Schematic …

Synnax v0.35.1

---

console/package.json
console/src/table/Table.tsx
console/src/table/external.ts

- **Linear Issue**: [SY-1672](https://linear.app/synnax/issue/SY-1672/fix-table-loading-in-workspace)
Fixes an issue where tables fail to load correctly in workspaces.

[console] - fixed table loading in workspace

---

console/src/hardware/task/Toolbar.tsx

- **Linear Issue**: [SY-1691](https://linear.app/synnax/issue/SY-1691/copy-link-from-task-toolbar)
Added a link item to task toolbar context menu.

SY-1691 Copy Link From Task Toolbar

---

console/src/layout/Modal.tsx
console/src/schematic/toolbar/Toolbar.tsx
console/src/table/Toolbar.tsx
pluto/src/align/Space.tsx
pluto/src/breadcrumb/Breadcrumb.css
pluto/src/breadcrumb/Breadcrumb.tsx
pluto/src/css/css.ts
pluto/src/dropdown/Dropdown.css
pluto/src/header/Title.tsx
pluto/src/menu/ContextMenu.css
pluto/src/modal/Modal.css
pluto/src/status/Notification.css
pluto/src/viewport/use.ts

- **Linear Issue**: [SY-1687](https://linear.app/synnax/issue/SY-1687/fix-padding-on-breadcrumbs)

Sy 1687 fix padding on breadcrumbs

---

console/src/lineplot/NavControls.tsx
console/src/palette/Tooltip.tsx
pluto/src/text/Keyboard.css
pluto/src/text/Keyboard.tsx
pluto/src/viewport/SelectMode.tsx

- **Linear Issue**: [SY-1675](https://linear.app/synnax/issue/SY-1705/fix-select-trigger-display)
Improves display of various `Text.Keyboard` elements across the UI. 

Sy 1705 fix select trigger display

---

console/release-spec.json
docs/site/src/pages/releases/0-36-0.mdx
docs/site/src/pages/releases/index.mdx

Linear Issue: [SY-1711](https://linear.app/synnax/issue/SY-1711/synnax-v036-release-notes)

Synnax v0.36.0 Release Notes

---

console/src/hardware/opc/task/Read.tsx

**Linear Issues**:
- [SY-1603](https://linear.app/synnax/issue/SY-1603/can-configure-opc-ua-task-if-sample-rate-is-less-than-array-size)
- [SY-1601](sy-1601-can-configure-an-opc-ua-read-task-with-a-stream-rate-greater)
Make sure to validate OPC UA Read Task methods before configuring.

Validate OPC UA Read Task Configuration before Configuring

---

docs/site/.astro/settings.json
docs/site/src/components/Diagram.astro
docs/site/src/components/Header.astro
docs/site/src/components/NextPrev.astro
docs/site/src/components/OnThisPage/OnThisPage.tsx
docs/site/src/components/PageNav/PageNav.astro
docs/site/src/components/PageNav/PageNav.tsx
docs/site/src/components/article/Article.astro
docs/site/src/components/code/Code.astro
docs/site/src/components/releases/Release.astro
docs/site/src/components/search/Search.astro
docs/site/src/components/search/Search.tsx
docs/site/src/layouts/Releases.astro
docs/site/src/layouts/Root.astro
docs/site/src/pages/releases/0-31-0.mdx
docs/site/src/pages/releases/0-32-0.mdx
docs/site/src/pages/releases/0-33-0.mdx
docs/site/src/pages/releases/0-34-0.mdx
docs/site/src/pages/releases/0-35-0.mdx
docs/site/src/pages/releases/0-36-0.mdx
docs/site/src/pages/releases/index.mdx
docs/site/src/util/algoliasearch.js
pluto/src/breadcrumb/Breadcrumb.spec.tsx
pluto/src/breadcrumb/Breadcrumb.tsx
pluto/src/dropdown/Dropdown.css
x/media/src/Icon/index.tsx

Sy 1721 breadcrumb links on docs site do not work

---

.github/PULL_REQUEST_TEMPLATE/rc.md

Edit QA steps for ontology context menus

---

.github/PULL_REQUEST_TEMPLATE/rc.md
console/src/layout/Menu.tsx
console/src/layout/hooks.ts

- **Linear Issue**: [SY-1773](https://linear.app/synnax/issue/)

Change Hotkeys

---

docs/site/.astro/settings.json
docs/site/src/components/OnThisPage/OnThisPage.astro
docs/site/src/components/OnThisPage/OnThisPage.tsx
docs/site/src/components/feedback/Feedback.astro
docs/site/src/components/feedback/Feedback.tsx
x/media/src/Icon/index.tsx

- **Linear Issue**: [SY-1826](https://linear.app/synnax/issue/SY-1826/add-feedback-form-to-documentation-site)
Adds a feedback form to the documentation site.

[docs/site] - added feedback form

---

console/src/table/Table.css
console/src/table/Table.tsx
console/src/table/Toolbar.tsx
console/src/table/external.ts
console/src/table/index.ts
console/src/table/migrations/index.ts
console/src/table/migrations/v0.ts
console/src/table/selectors.ts
console/src/table/slice.ts

- **Linear Issue**: [SY-1761](https://linear.app/synnax/issue/SY-1761/delete-column-on-cell-does-not-work)
Fixed a bug where calling delete column from the context menu of a table cell did not actually delete the column.

SY-1761: Fix Delete Column on Table Cell

---

console/src/palette/Palette.tsx
console/src/palette/command.tsx
console/src/workspace/export.ts
console/src/workspace/services/palette.tsx

SY-1893 - Add Export Workspace Command to Command Palette

---

console/src/hardware/common/task/ChannelList.tsx
console/src/hardware/common/task/Form.css
console/src/hardware/common/task/layouts/ChannelList.tsx
console/src/hardware/common/task/layouts/ListAndDetails.tsx
pluto/src/hardware/device/Select.tsx
pluto/src/header/Actions.tsx
pluto/src/theming/core/theme.ts

- **Linear Issue**: [SY-2052](https://linear.app/synnax/issue/)
Fixes weird resizing issues when changing channel types. 

SY-2052 - Cleaned Up Task Details View

---

driver/cmd/exec.cpp
driver/cmd/login.cpp
driver/cmd/service.cpp
driver/cmd/start.cpp
driver/cmd/version.cpp
driver/daemon/daemon_nilinuxrt.cpp
driver/rack/config_test.cpp
driver/rack/file.cpp
driver/rack/persist.cpp
driver/rack/rack.h
driver/rack/remote.cpp
driver/task/manager.cpp
synnax/pkg/distribution/distribution.go
synnax/pkg/service/hardware/embedded/driver.go
synnax/pkg/service/hardware/embedded/enabled.go
x/cpp/xlog/xlog.h

- **Linear Issue**: [SY-2099](https://linear.app/synnax/issue/SY-2099)

SY-2099 Fix Dead Rack Warning

---

console/src/hardware/common/task/Task.tsx
console/src/hardware/labjack/task/Read.tsx
console/src/hardware/ni/task/AnalogWrite.tsx
console/src/hardware/opc/device/Connect.tsx

Random code changes to stop errors from happening in the task.

Minor Task Touchups

---

client/py/examples/stream_write.py
console/src/hardware/common/task/Form.tsx
console/src/hardware/common/task/Rack.tsx

- **Linear Issue**: [SY-1992](https://linear.app/synnax/issue/SY-1992/show-rack-on-task-form)
Show the rack on the console task form

SY-1992 Show Rack on Task Form

---

driver/rack/factories.cpp
synnax/pkg/service/hardware/tracker/tracker.go
x/cpp/telem/telem.h
x/cpp/telem/telem_test.cpp
x/go/telem/series_test.go
x/go/telem/telem.go
x/go/telem/telem_test.go

- **Linear Issue**: [SY-2128](https://linear.app/synnax/issue/SY-2128)

[driver] - fixed driver heartbeat

---

alamos/py/poetry.lock
alamos/py/pyproject.toml
client/py/examples/control/press/simulated_daq.py
client/py/poetry.lock
client/py/pyproject.toml
client/py/synnax/__init__.py
client/py/synnax/auth.py
client/py/tests/test_auth.py
freighter/py/freighter/mock.py
freighter/py/poetry.lock
freighter/py/pyproject.toml

- **Linear Issue**: [SY-2144](https://linear.app/synnax/issue/SY-2144/update-python-dependencies)
Update Python dependencies and run `isort`

SY-2144: Update Python Dependencies

---

.github/PULL_REQUEST_TEMPLATE/rc.md
console/src/hardware/task/sequence/globals.ts
driver/sequence/plugins/BUILD.bazel
driver/sequence/plugins/plugins.h
driver/sequence/plugins/time.cpp
driver/sequence/plugins/time_test.cpp

- **Linear Issue**: [SY-2076](https://linear.app/synnax/issue/SY-2076)
Adds sequence steps to QA, implements some missing tests for sequence timing methods, and adds remaining auto-complete suggestions for built-in sequence functions. 

SY-2076 - Add Sequence Steps to QA, Implement tests for timing plugins, and add auto-complete to sequence editor

---

console/src/user/Register.tsx

- **Linear Issue**: [SY-2174](https://linear.app/synnax/issue/SY-2174)
Fixes padding on back left user registration dialog.

SY-2174 - Fix Padding on User Registration Dialog

---

console/src/hardware/task/layouts.ts
console/src/hardware/task/ontology.tsx

- **Linear Issue**: [SY-1955](https://linear.app/synnax/issue/SY-1955/fix-edit-configuration-for-control-sequences-in-task-toolbar)
Made sure the correct name for a task is placed when it is opened from the resources or task toolbar.

SY-1955: Fix Opening Tasks from Context Menu

---

client/py/examples/arduino/read_driver.py
client/py/examples/arduino/read_write_driver.py
client/py/examples/calculated_channels.py
client/py/examples/control/abort/simulated_daq.py
client/py/examples/control/press/simulated_daq.py
client/py/examples/control/tpc/simulated_daq.py
client/py/examples/dev/calc_channel_stress.py
client/py/examples/dev/multi_stream.py
client/py/examples/multi-rate-calculated/interpolation.py
client/py/examples/multi-rate-calculated/simple_average.py
client/py/examples/multi-rate-calculated/simulated_daq.py
client/py/examples/simulation.py
client/py/examples/stream_write.py
client/py/pyproject.toml
client/py/synnax/cli/ts_convert.py
client/py/synnax/framer/writer.py
client/py/tests/test_framer.py
docs/site/src/pages/reference/python-client/write-data.mdx
freighter/py/freighter/stream.py

- **Linear Issue**: [SY-2181](https://linear.app/synnax/issue/SY-2181)
Fixes an issue where the python client writer would fail to accumulate errors correctly, and cause difficult to debug issues. Also updates Python client docs to add docs for error handling.

SY-2181 - Python Client Better Communication of Writer Errors

---

console/src/channel/Calculated.tsx
console/src/code/lua/lsp.ts
console/src/code/phantom.ts
console/src/code/useSuggestChannels.tsx
console/src/hardware/task/sequence/Sequence.tsx
freighter/go/fhttp/stream.go
freighter/go/fhttp/unary.go
freighter/go/fmock/unary.go
synnax/pkg/service/hardware/embedded/enabled.go

- **Linear Issue**: [SY-2164](https://linear.app/synnax/issue/SY-2164)
Fixes issues with channel auto-complete on calc channels. Accidentally checked out off of another branch, so merging it into that one to keep good diff.

SY-2164 - Fix Auto Complete Not Working On Calc Channels

---

console/src/permissions/Edit.tsx
console/src/user/services/ontology.tsx

- **Linear Issue**: [SY-2175](https://linear.app/synnax/issue/SY-2175/failed-to-retrieve-user-permissions)

SY-2175: Fix User Permissions Dialog

---

client/ts/examples/node/basicReadWrite.js
client/ts/examples/node/liveStream.js
client/ts/examples/node/seriesAndFrames.js
client/ts/examples/node/streamWrite.js
client/ts/src/framer/writer.spec.ts
client/ts/src/framer/writer.ts
docs/site/src/pages/reference/typescript-client/write-data.mdx
synnax/pkg/distribution/framer/writer/synchronizer.go

- **Linear Issue**: [SY-2182](https://linear.app/synnax/issue/SY-2182)

SY-2182 - Typescript Client Better Communication of Writer Errors

---

driver/labjack/read_task.h

- **Linear Issue**: [SY-2130](https://linear.app/synnax/issue/SY-2130)
Fixes missing application of configuration for thermocouples in LabJack read task. 

SY-2130 - Fix LabJack Thermocouple

---

client/cpp/synnax.h
driver/rack/rack.cpp
driver/rack/rack.h
driver/task/common/scan_task.h
driver/task/manager.cpp
driver/task/task.h
synnax/cmd/start.go
synnax/pkg/service/hardware/embedded/enabled.go
synnax/pkg/service/label/label_test.go
synnax/pkg/service/label/service.go
x/cpp/breaker/breaker.h
x/cpp/xlog/xlog.h

- **Linear Issue**: [SY-2104](https://linear.app/synnax/issue/SY-2104)
Improves the early shutdown mechanics for both the driver and server. Also when through and verified that the TLS certificate setup works correctly. 

SY-2104 - Improved Driver & Server Early Shutdown Mechanics

---

console/src/Console.tsx
pluto/src/index.ts
pluto/src/input/DragButton.tsx

- **Linear Issue**: [SY-2192](https://linear.app/synnax/issue/SY-2192/fix-improper-effect-cleanup-in-consoletsx)
- Exported `preventDefault` and `stopPropagation` from Pluto
- Properly clean up the event listener in `useBlockDefaultDropBehavior`
- [] I have updated user-facing documentation to reflect the changes.

SY-2192: Fix Bad Event Listener Cleanup

---

docs/site/src/pages/reference/control/embedded/get-started.mdx
docs/site/src/pages/reference/control/embedded/recipes.mdx
docs/site/src/pages/reference/control/embedded/reference.mdx
docs/site/src/pages/reference/control/get-started.mdx
docs/site/src/pages/reference/device-drivers/labjack/get-started.mdx
docs/site/src/pages/reference/device-drivers/ni/get-started.mdx

SY-2204 - Pull Shark - Doc Improvements

---

.github/workflows/test.alamos.yaml
.github/workflows/test.aspen.yaml
.github/workflows/test.cesium.yaml
.github/workflows/test.freighter.yaml
.github/workflows/test.synnax.yaml
.github/workflows/test.updates.yaml
.github/workflows/test.x.yaml

- **Linear Issue**: [SY-2231](https://linear.app/synnax/issue/SY-2231/fix-script-execution-in-ci-cd)
Run scripts in CI / CD explicitly with the `bash` command to make sure they are executable.

SY-2231 Fix Script Execution in CI / CD

---

pluto/src/hardware/device/Select.tsx

- **Linear Issue**: [SY-2264](https://linear.app/synnax/issue/SY-2264/add-rack-to-device-selection-list)
Added the rack name to the device selection list.

Add rack name to device selection list

---

console/src/hardware/common/task/Form.tsx

Fix LabJack taring

---

console/src/hardware/opc/task/Read.tsx

Make sure OPC UA Read Task always sets arraySize to 1

---

docs/site/src/pages/releases/0-40-0.mdx
docs/site/src/pages/releases/index.mdx

- **Linear Issue**: [SY-2313](https://linear.app/synnax/issue/SY-2313)
Version 40 release notes. 

SY-2313: Version 0.40.0 Release Notes

---

console/package.json
console/src/lineplot/LinePlot.tsx

- **Linear Issue**: [SY-2341](https://linear.app/synnax/issue/SY-2341)
Fixed line plot rule positioning so that it doesn't drift across plots.

SY-2341: Patched Rule Positioning

---

client/py/examples/basic_read_write.py
console/package.json
package.json
pluto/package.json
pluto/src/viewport/Mask.tsx
pluto/src/viewport/SelectMode.tsx
pluto/src/viewport/use.ts
pluto/src/vis/axis/canvas.ts
pluto/src/vis/axis/preciseTimeScale.spec.ts
pluto/src/vis/axis/preciseTimeScale.ts
pluto/src/vis/axis/ticks.ts
pluto/src/vis/legend/Container.css
pluto/src/vis/legend/Simple.tsx
pluto/src/vis/line/aether/line.ts
pluto/src/vis/lineplot/Line.tsx
pluto/src/vis/lineplot/LinePlot.tsx
pluto/src/vis/lineplot/tooltip/aether/tooltip.ts
pnpm-lock.yaml
x/media/src/Icon/index.tsx
x/ts/src/telem/telem.ts

- **Linear Issue**: [SY-2272](https://linear.app/synnax/issue/SY-2272)

SY-2272: Implement High Precision Line Plot Zooming

---

console/src/hardware/device/Toolbar.tsx
console/src/hardware/labjack/task/InputChannelForms.tsx
console/src/hardware/ni/task/CustomScaleForm.tsx
console/src/lineplot/NavControls.tsx
console/src/permissions/Edit.tsx
console/src/schematic/toolbar/Properties.tsx
docs/site/src/components/OnThisPage/OnThisPage.tsx
docs/site/src/components/releases/ReleaseList.tsx
pluto/src/mosaic/Mosaic.spec.tsx
pluto/src/table/Table.tsx
pluto/src/vis/schematic/OrientationControl.css
pluto/src/vis/schematic/SelectOrientation.tsx
pluto/src/vis/schematic/primitives/Primitives.tsx

Refactor of needles fragments and fix orientation selector

---

console/src/layout/types/v0.ts
console/src/layout/types/v5.ts
console/src/layouts/nav/drawerItems.ts
console/src/ontology/Toolbar.tsx
console/src/ontology/external.ts
console/src/range/Toolbar.tsx
console/src/range/services/palette.tsx
pluto/src/mosaic/tree.ts

Remove Range explorer and add  back in resources toolbar

---

console/package.json
console/src/group/services/ontology.tsx
console/src/layouts/Main.tsx
console/src/layouts/Mosaic.tsx
console/src/ontology/Tree.tsx
pluto/src/tree/Tree.spec.tsx
pluto/src/tree/core.ts
pluto/src/triggers/Provider.tsx
pluto/src/triggers/Triggers.spec.tsx
pluto/src/triggers/triggers.ts
pluto/src/vis/diagram/Diagram.tsx
pluto/src/vis/lineplot/range/Provider.tsx
pluto/src/vis/lineplot/range/aether/provider.ts
x/go/telem/telem_test.go

SY-2442 - Various Minor Console Fixes

---

console/package.json
console/src/hardware/common/task/Task.tsx
console/src/hardware/opc/task/Read.tsx
console/src/hardware/opc/task/Write.tsx
console/src/hardware/opc/task/types.ts

Fix the OPC UA Task Config Parsing with datatypes that don't exist. Also add checks for haul items and remove type assertions.

Fix OPC UA Task Config Parsing

---

console/src/range/overview/MetaData.tsx

- **Linear Issue**: [SY-2470](https://linear.app/synnax/issue/SY-2470)

SY-2470 - Fix Style of Range Meta Data Copy Button

---

console/src/hardware/task/sequence/types.ts

- **Linear Issue**: [SY-2482](https://linear.app/synnax/issue/SY-2482)

SY-2482 - Improved Control Sequence Placeholder Text

---

pluto/src/telem/aether/remote.spec.ts
pluto/src/telem/aether/remote.ts
pluto/src/vis/lineplot/range/aether/provider.ts

- **Linear Issue**: [SY-2483](https://linear.app/synnax/issue/SY-2483)

SY-2483 - Fixed Live Range Display on Plots

---

client/ts/src/control/client.ts
client/ts/src/framer/streamer.ts
freighter/go/fhttp/stream.go
freighter/go/stream_test.go

- **Linear Issue**: [SY-####](https://linear.app/synnax/issue/SY-2466)

SY-2486 - Fix HTTP Websocket Write Deadline Behavior

---

console/package.json
pluto/package.json
pluto/src/vis/value/aether/value.ts

SY-2488 - Fix Value Background Color Rendering

---

console/package.json
console/src/schematic/selectors.ts

SY-2489 - Hotfix Schematic Edge Selection

---

.github/PULL_REQUEST_TEMPLATE/issue.md

[SY-2490](https://linear.app/synnax/issue/SY-2490/update-pr-template)
Remove unhelpful fields from the PR template so filling it out is slightly less of a chore.

SY-2490: Remove unhelpful fields from PR template

---

docs/site/src/pages/reference/device-drivers/ni/digital-read-task.mdx
docs/site/src/pages/reference/device-drivers/ni/digital-write-task.mdx

[SY-2548](https://linear.app/synnax/issue/SY-2548/fix-typo-in-ni-digital-task-documentation)
Fix typos in NI digital task documentation.

SY-2548: Fix typos in NI digital task documentation

---

console/src/channel/services/Toolbar.tsx
console/src/hardware/device/Toolbar.tsx
console/src/ontology/Toolbar.tsx
console/src/ontology/Tree.tsx
console/src/user/services/Toolbar.tsx
console/src/version/Info.tsx
console/src/workspace/services/Toolbar.tsx

[SY-2567](https://linear.app/synnax/issue/SY-2567/remove-undefined-from-react-query-returns)
Remove `undefined` from React Query returns

SY-2567: Remove `undefined` from React Query returns

---

console/src/hardware/opc/device/Connect.tsx

[SY-2566](https://linear.app/synnax/issue/SY-2566/fix-security-policy-padding-on-opc-ua-server-connect-modal)

SY-2566: Widen OPC UA connect server modal

---

docs/site/src/pages/reference/console/calculated-channels.mdx
docs/site/src/pages/reference/console/channels.mdx
docs/site/src/pages/reference/console/clusters.mdx
docs/site/src/pages/reference/console/line-plots.mdx
docs/site/src/pages/reference/console/schematics.mdx
docs/site/src/pages/reference/console/ui-overview.mdx
docs/site/src/pages/reference/device-drivers/opc-ua/read-task.mdx
docs/site/src/pages/reference/device-drivers/opc-ua/write-task.mdx

[SY-2544](https://linear.app/synnax/issue/SY-2544/fix-table-sizing-on-documentation-site)
Fix table sizing on documentation site.

SY-2544: Fix table sizing on documentation site

---

x/ts/src/telem/series.spec.ts
x/ts/src/telem/series.ts

[SY-2574](https://linear.app/synnax/issue/SY-2574/fix-log-text-disappearing-when-you-hit-the-pause-icon)
Fixed log text disappearing when you hit the pause icon.

SY-2574 - Fix Log Text Disappearing When You Hit the Pause Icon

---

console/src/schematic/selectors.ts
console/src/schematic/toolbar/Toolbar.tsx

[SY-2586](https://linear.app/synnax/issue/SY-2586/fix-schematic-editable-error)
Fix the schematic editable error in the schematic toolbar.

SY-2586: Fix schematic editable error

---

docs/site/src/pages/releases/0-42-0.mdx
docs/site/src/pages/releases/0-43-0.mdx
docs/site/src/pages/releases/index.mdx

[SY-2582](https://linear.app/synnax/issue/SY-2582/synnax-v043-release-notes)
Add the v0.43 release notes.

SY-2582: Synnax v0.43 Release Notes

---

console/package.json
console/src/schematic/Schematic.tsx
console/src/schematic/export.ts
console/src/schematic/selectors.ts
console/src/schematic/toolbar/Control.tsx
console/src/schematic/toolbar/Properties.tsx

[SY-2622](https://linear.app/synnax/issue/SY-2622/fix-schematic-toolbar-errors)
Fix the schematic toolbar errors by creating a `selectRequired` and `selectOptional` selector and clearly marking which selectors will throw an error with the word required in there function names.

Sy-2622: Fix Schematic Toolbar Errors

---

client/ts/package.json
client/ts/src/hardware/device/payload.ts
client/ts/src/hardware/rack/payload.ts
client/ts/src/hardware/task/payload.ts
console/package.json
pluto/package.json

[SY-2627](https://linear.app/synnax/issue/SY-2627/fix-zod-error-on-invalid-state-variant)
Fixed the Zod errors on invalid state variant by piping states with an empty string to "info". Will put adding server-side validation and checking all driver calls to [SY-2618](https://linear.app/synnax/issue/SY-2618/standardize-status-specs)

SY-2627 Fix Zod Error on Invalid State Variant

---

.github/workflows/test.console.yaml
package.json

[SY-2626](https://linear.app/synnax/issue/SY-2626/fix-console-ci-memory-issues)
Fix Console CI memory issues by checking types instead of building the Console.

SY-2626: Fix Console CI Memory Issues

---

docs/site/src/layouts/Root.astro
docs/site/src/middleware.ts
docs/site/src/pages/reference/cluster/requirements.mdx

[SY-2650](https://linear.app/synnax/issue/SY-2650/update-system-requirements-docs)

SY-2650 - Update System Requirements Docs

---

.github/workflows/deploy.synnax.yaml
.github/workflows/test.client.yaml
.github/workflows/test.driver.yaml
.github/workflows/test.freighter.yaml
.github/workflows/test.migration.yaml

[SY-2633](https://linear.app/synnax/issue/SY-2663/fix-earthly-in-ci)
Fix earthly rate limiting.

SY-2663 - Authenticate Earthly Requests in CI

---

console/src/schematic/Schematic.tsx
console/src/schematic/toolbar/Toolbar.tsx
pluto/src/aether/aether/aether.bench.ts
pluto/src/aether/aether/aether.spec.ts
pluto/src/aether/aether/aether.ts
pluto/src/aether/main.tsx
pluto/src/button/Toggle.tsx
pluto/src/hooks/useRequiredContext.ts
pluto/src/synnax/Provider.tsx
pluto/src/telem/aether/context.ts
pluto/src/telem/aether/provider.ts
pluto/src/telem/control/Legend.tsx
pluto/src/telem/control/aether/chip.ts
pluto/src/telem/control/aether/indicator.ts
pluto/src/vis/schematic/Forms.css
pluto/src/vis/schematic/Forms.tsx
pluto/src/vis/schematic/SelectOrientation.css
pluto/src/vis/schematic/SelectOrientation.tsx

Addresses:
[SY-2675](https://linear.app/synnax/issue/SY-2675/fix-schematic-orientation-controls)
[SY-2674](https://linear.app/synnax/issue/SY-2674/fix-schematic-button)

SY-2675 - Fix Schematic Orientation Controls

---

pluto/src/telem/aether/transformers.spec.ts
pluto/src/telem/aether/transformers.ts
x/ts/src/telem/series.spec.ts
x/ts/src/telem/series.ts

[SY-2759](https://linear.app/synnax/issue/SY-2759/fix-line-plot-averaging)

SY-2759 - Fixed Line Plot Averaging

---

console/package.json
pluto/package.json
pluto/src/vis/light/aether/light.ts
pluto/src/vis/light/use.ts
pluto/src/vis/schematic/Forms.tsx
pluto/src/vis/schematic/Symbols.tsx

[SY-2806](https://linear.app/synnax/issue/SY-2806/fix-light-schematic-element)
Fix an issue with the light schematic element not updating it's state.

SY-2806: Fix light schematic element

---

console/src/table/Toolbar.tsx

Addresses:
[SY-2864](https://linear.app/synnax/issue/SY-2864/cant-edit-table-value-from-form) - Can't edit table value on form
[SY-2865](https://linear.app/synnax/issue/SY-2865/not-allowed-to-set-stale-timeout-on-table-value) - Not allowed to set stale timeout on table value.

SY-2864 - Fixed Table Form Editing

---

console/src/components/menu/HardReloadItem.tsx
console/src/link/useDeep.ts
console/src/store.ts
console/src/workspace/services/link.ts

[SY-2843](https://linear.app/synnax/issue/SY-2843/fix-link-copy-and-open-perma-opening-a-link-on-reload)
Fixed the problem where hard reloading would open the Console with the same link.

SY-2843: Fix Deep Link and Hard Reload Interactions

---

core/pkg/service/metrics/metrics_test.go

[SY-2894](https://linear.app/synnax/issue/SY-2894/fix-node-metrics-test)
Fix the node metrics test that has been failing in CI.

SY-2894: Fix Node Metrics Test

---

console/src/range/Create.tsx
console/src/range/overview/Details.tsx

[SY-2833](https://linear.app/synnax/issue/SY-2833/dialog-positioning-on-label-selector-is-bad)

SY-2833 - Fix Dialog Positioning on Label Selector

---

console/src/hardware/common/device/Provider.tsx
console/src/hardware/common/task/layouts/ChannelList.tsx
console/src/hardware/task/Toolbar.tsx
console/src/lineplot/toolbar/Annotations.tsx
console/src/log/Log.tsx
console/src/ontology/Tree.tsx
console/src/range/Toolbar.tsx
console/src/schematic/toolbar/Symbols.tsx
console/src/schematic/toolbar/Toolbar.tsx
console/src/workspace/services/Toolbar.tsx

Add empty content for workspace toolbar and fix emptyaction text in other places

---

pluto/src/vis/line/aether/line.spec.ts
pluto/src/vis/line/aether/line.ts
x/ts/src/telem/series.ts

[SY-2839](https://linear.app/synnax/issue/SY-2839/averaging-still-causing-problems)

SY-2839: Fix Line Plot Averaging

---

console/src/hardware/task/sequence/types.ts

[SY-2901](https://linear.app/synnax/issue/SY-2901/rack-validation-on-control-sequence-still-fails)

SY-2901: Fixed Rack Key Validation on Sequences

---

pluto/src/schematic/symbol/Forms.tsx

[SY-2886](https://linear.app/synnax/issue/SY-2886/auto-fit-on-text-box-needs-to-be-improved)

SY-2886 - Fix Auto Fit on Text Box

---

console/src/workspace/services/ontology.tsx

[SY-2848](https://linear.app/synnax/issue/SY-2848/dragging-and-dropping-onto-top-level-workspaces-doesnt-work-ontology)

SY-2848: Fix Dragging and Dropping onto Top Level Workspaces

---

console/src/hardware/common/task/Form.tsx
console/src/layout/external.ts
console/src/layout/useSyncName.spec.tsx
console/src/layout/useSyncName.ts
console/src/range/overview/Details.tsx

[SY-2832](https://linear.app/synnax/issue/SY-2871/renaming-a-task-from-layout-windows-does-not-stop-and-rename)

SY-2871: Fix Layout Name Syncing on Tasks

---

console/src/workspace/services/import.ts

[SY-2898](https://linear.app/synnax/issue/SY-2898/fix-task-importing-inside-workspace-import)
Fix workspace importing with tasks by updating the layout and workspace slice before placing additional layouts like tasks.

SY-2898: Fix Workspace Importing with tasks

---

.github/workflows/deploy.core.yaml
.github/workflows/test.integration.yaml

[SY-2908](https://linear.app/synnax/issue/SY-2908/update-integration-ci-scripts)
Update the CI scripts with proper runner names.

SY-2908: Update CI scripts with proper runners

---

.github/workflows/deploy.core.yaml

[SY-2910](https://linear.app/synnax/issue/SY-2910/fix-macos-core-signing)
Fix the macOS core signing by adding a timeout before the sign command so the macOS keychain doesn't stall.

SY-2910: Fix macOS Core Signing

---

.github/workflows/deploy.console.yaml

[SY-2948](https://linear.app/synnax/issue/SY-2948/fix-console-deployment-script)
Fix the console deployment script that uses the new node action.

SY-2948: Fix Console Deployment Script

---

console/src/layout/useDropOutside.ts
drift/src/configureStore.ts

[SY-2964](https://linear.app/synnax/issue/SY-2964/drift-fix-window-drag-and-drop-outside)
Fix window drag and drop outside

SY-2964: Drift Fix Window Drag and Drop Outside

---

pluto/src/telem/client/streamer.ts

[SY-2983](https://linear.app/synnax/issue/SY-2983/fix-issues-with-high-performance-frame-codec-on-rapid-streamer-sets)

SY-2983: Fix Issues with High Performance Frame Codec on Rapid

---

console/src/hardware/opc/device/Browser.tsx
pluto/src/flux/retrieve.ts

[SY-2994](https://linear.app/synnax/issue/SY-2994/fix-opc-ua-failed-to-retrieve-node-error)

SY-2994: Fix OPC UA Failed to Retrieve Node

---

pluto/src/flux/list.spec.ts
pluto/src/flux/list.ts

[SY-2991](https://linear.app/synnax/issue/SY-2991/fix-channel-renaming-synchronization)

SY-2991: Fix Channel Renaming Synchronization

---

aspen/internal/kv/kv.go
core/pkg/service/arc/runtime.go
core/pkg/service/arc/runtime/runtime.go
core/pkg/service/arc/runtime/std/status.go
core/pkg/service/status/writer.go

SY-2988: Arc Runtime Isolation

---

integration/framework/test_case.py
integration/framework/utils.py
integration/tests/console/plot_abcd.py
integration/tests/latency/abcd.py

[SY-3022](https://linear.app/synnax/issue/SY-3022/update-get-machine-info-for-win11)

SY-3022: Get Machine Info - Win11 Compatibility

---

console/src/store.ts

[SY-3033](https://linear.app/synnax/issue/SY-3033/enable-console-prerendering)
Enabled prerendering for Drift in the Console based off of whether the environment is production or not.

Conditionally enable prerendering in the console

---

console/src/group/useCreateFromSelection.ts

[SY-3074](https://linear.app/synnax/issue/SY-3074/fix-empty-group-creation)

SY-3074: Fix Empty Group Creation

---

.github/workflows/deploy.console.yaml
.github/workflows/deploy.core.yaml
.github/workflows/deploy.ts.yaml
.github/workflows/test.alamos.ts.yaml
.github/workflows/test.client.yaml
.github/workflows/test.console.yaml
.github/workflows/test.drift.yaml
.github/workflows/test.freighter.yaml
.github/workflows/test.integration.yaml
.github/workflows/test.media.yaml
.github/workflows/test.pluto.yaml
.github/workflows/test.x.ts.yaml

SY-1862: Enable Turbo-Repo Remote Caching
